// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `err`, `map_client_error`, `map_sdk_error`, `relay_to_dto`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<WarrenClientFrb>>
abstract class WarrenClientFrb implements RustOpaqueInterface {
  /// The SS58 `wb...` address of the bound identity.
  Future<String> address();

  /// Builds a client from a mnemonic and the account API configuration.
  ///
  /// The mnemonic is consumed here and not retained; the engine zeroizes the
  /// derived signing key on drop.
  static Future<WarrenClientFrb> create(
          {required String mnemonic,
          required String apiBase,
          required String serverPubkeyPin,
          String? multihopRootPin}) =>
      WarrenRustBridge.instance.api.crateApiClientWarrenClientFrbCreate(
          mnemonic: mnemonic,
          apiBase: apiBase,
          serverPubkeyPin: serverPubkeyPin,
          multihopRootPin: multihopRootPin);

  /// Fetches and verifies the signed relay list, returning the exits.
  Future<List<ExitInfoDto>> listExits();

  /// Redeems a voucher and returns the new expiry (Unix seconds).
  Future<BigInt> redeemVoucher({required String secret});

  /// Unix-seconds subscription expiry (`0` means no active subscription).
  Future<BigInt> subscriptionExpiry();
}

/// An exit advertised by the verified signed relay list.
///
/// `supports_port_forwarding` is not carried in the relay list: inbound port
/// forwarding is negotiated per connection at handshake time, so it is reported
/// as `false` here and confirmed once a session is established. `load` is not
/// advertised either and is left unset.
class ExitInfoDto {
  /// Stable, operator-assigned exit identifier (survives key rotation).
  final String id;

  /// ISO country code.
  final String country;

  /// City name.
  final String city;

  /// Whether the exit attests IPv6 egress.
  final bool supportsIpv6;

  /// Whether inbound port forwarding is known to be available (always false
  /// at listing time; negotiated at connect).
  final bool supportsPortForwarding;

  /// Optional load hint in `[0.0, 1.0]`, when advertised.
  final double? load;

  const ExitInfoDto({
    required this.id,
    required this.country,
    required this.city,
    required this.supportsIpv6,
    required this.supportsPortForwarding,
    this.load,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      country.hashCode ^
      city.hashCode ^
      supportsIpv6.hashCode ^
      supportsPortForwarding.hashCode ^
      load.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExitInfoDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          country == other.country &&
          city == other.city &&
          supportsIpv6 == other.supportsIpv6 &&
          supportsPortForwarding == other.supportsPortForwarding &&
          load == other.load;
}
