// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'datapath.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `err`, `map_client_error`, `map_sdk_error`, `relay_to_dto`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<WarrenClientFrb>>
abstract class WarrenClientFrb implements RustOpaqueInterface {
  /// The SS58 `wb...` address of the bound identity.
  Future<String> address();

  /// The account server's view of this connection (signed `GET /v1/check`):
  /// whether traffic egresses from a registered Warren exit, and which one.
  /// Confirms a tunnel end-to-end against the backend rather than a third-party
  /// IP echo.
  Future<TunnelCheckDto> check();

  /// Opens a self-healing multihop proxy to the exit whose Ed25519 identity is
  /// `exit_pubkey_hex` (the `id` from [`list_exits`]), binding the local
  /// listeners. Proxy mode always uses multihop, which real exits require.
  ///
  /// When `failover_exit_pubkeys_hex` is non-empty the datapath runs over the
  /// prioritized list `[exit_pubkey_hex, ..failover]`: it sticks with the first
  /// exit that connects and only rotates to the next candidate when the current
  /// one fails to (re)establish, so one broken exit no longer wedges the session.
  ///
  /// Connect failures after this returns surface as connection state on the
  /// session, not as an error here.
  Future<WarrenSessionFrb> connectProxy(
      {required String exitPubkeyHex,
      required List<String> failoverExitPubkeysHex,
      required String socks5Listen,
      String? httpListen,
      String? dnsServer});

  /// Builds a client from a mnemonic and the account API configuration.
  ///
  /// The mnemonic is consumed here and not retained; the engine zeroizes the
  /// derived signing key on drop.
  static Future<WarrenClientFrb> create(
          {required String mnemonic,
          required String apiBase,
          required List<String> apiAlternativeHosts,
          required String serverPubkeyPin,
          String? multihopRootPin,
          required bool daita,
          String? daitaMachine,
          required bool requestIpv6,
          String? stateDir}) =>
      WarrenRustBridge.instance.api.crateApiClientWarrenClientFrbCreate(
          mnemonic: mnemonic,
          apiBase: apiBase,
          apiAlternativeHosts: apiAlternativeHosts,
          serverPubkeyPin: serverPubkeyPin,
          multihopRootPin: multihopRootPin,
          daita: daita,
          daitaMachine: daitaMachine,
          requestIpv6: requestIpv6,
          stateDir: stateDir);

  /// Permanently deletes the account bound to this identity (signed
  /// `DELETE /v1/account`). App stores require an in-app account-deletion path.
  Future<void> deleteAccount();

  /// Fetches and verifies the signed relay list, returning the exits.
  Future<List<ExitInfoDto>> listExits();

  /// Redeems a voucher and returns the new expiry (Unix seconds).
  Future<BigInt> redeemVoucher({required String secret});

  /// Unix-seconds subscription expiry (`0` means no active subscription).
  Future<BigInt> subscriptionExpiry();
}

/// An exit advertised by the verified signed relay list. Only fields the relay
/// list actually carries are surfaced; port-forwarding is negotiated per
/// connection (not known at listing time).
class ExitInfoDto {
  /// Stable, operator-assigned exit identifier (survives key rotation).
  final String id;

  /// ISO country code.
  final String country;

  /// City name.
  final String city;

  /// Whether the exit attests IPv6 egress.
  final bool supportsIpv6;

  /// The exit's X.509 cover domain (ADR-0004 mimicry), when it advertises one.
  /// Such exits require cover-cert dialing the engine does not do yet, so an app
  /// can use this to pre-filter exits it cannot reach.
  final String? coverDomain;

  /// Relative selection weight the relay list advertises for load balancing.
  final BigInt weight;

  /// Whether the relay list marks the exit currently active.
  final bool isActive;

  const ExitInfoDto({
    required this.id,
    required this.country,
    required this.city,
    required this.supportsIpv6,
    this.coverDomain,
    required this.weight,
    required this.isActive,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      country.hashCode ^
      city.hashCode ^
      supportsIpv6.hashCode ^
      coverDomain.hashCode ^
      weight.hashCode ^
      isActive.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExitInfoDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          country == other.country &&
          city == other.city &&
          supportsIpv6 == other.supportsIpv6 &&
          coverDomain == other.coverDomain &&
          weight == other.weight &&
          isActive == other.isActive;
}

/// The account server's view of the caller's connection, from a signed
/// `GET /v1/check`. Lets an app confirm against the backend whether its traffic
/// egresses from a registered Warren exit, and where.
class TunnelCheckDto {
  /// The public IP the account server observed for this call.
  final String ip;

  /// True when `ip` is a registered Warren exit (traffic is tunneled).
  final bool isExit;

  /// Exit country (ISO 3166-1 alpha-2), when `is_exit`.
  final String? country;

  /// Exit city, when known.
  final String? city;

  const TunnelCheckDto({
    required this.ip,
    required this.isExit,
    this.country,
    this.city,
  });

  @override
  int get hashCode =>
      ip.hashCode ^ isExit.hashCode ^ country.hashCode ^ city.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TunnelCheckDto &&
          runtimeType == other.runtimeType &&
          ip == other.ip &&
          isExit == other.isExit &&
          country == other.country &&
          city == other.city;
}
