// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `new`, `to_dto`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<WarrenSessionFrb>>
abstract class WarrenSessionFrb implements RustOpaqueInterface {
  /// Tears the connection down and releases its datapath resources.
  /// Idempotent: a second call is a no-op.
  Future<void> disconnect();

  /// The bound local HTTP CONNECT endpoint, if one was requested.
  Future<String?> httpEndpoint();

  /// The bound local SOCKS5 endpoint, for example `127.0.0.1:51234`.
  Future<String> socks5Endpoint();

  /// Streams connection-state transitions, emitting the current state first so
  /// a late listener is never left without one.
  Stream<ConnectionStateDto> states();
}

/// Lifecycle state of a connection, mirrored for Dart as a plain enum.
enum ConnectionStateDto {
  /// The initial connect attempt is in flight.
  connecting,

  /// A connection is established.
  connected,

  /// A previous attempt failed; a retry is in flight after backoff.
  reconnecting,

  /// Every attempt failed; the supervisor gave up.
  failed,
  ;
}
