// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `fatal_to_dto`, `migration_to_dto`, `new`, `new`, `outcome_to_dto`, `to_dto`, `to_engine`, `to_engine`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<WarrenForwardedPortFrb>>
abstract class WarrenForwardedPortFrb implements RustOpaqueInterface {
  /// The current external port remote peers reach the app on, or `None` while
  /// the tunnel is down or before the first mapping is granted.
  Future<int?> externalPort();

  /// Streams external-port changes (re-mappings across reconnects), emitting
  /// the current value first so a late listener always gets one.
  Stream<int?> externalPorts();

  /// The local internal port being forwarded.
  Future<int> internalPort();

  /// Streams follow outcomes (doc 59): what happened to this rule's external
  /// port on each (re)establish (kept, changed, held back by a conflict, or
  /// failed). Emits the latest outcome first, if any, so a late listener is
  /// not left without one.
  Stream<PortFollowOutcomeDto> outcomes();

  /// Tears the forward down. Idempotent: a second call is a no-op.
  Future<void> shutdown();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<WarrenSessionFrb>>
abstract class WarrenSessionFrb implements RustOpaqueInterface {
  /// Tears the connection down and releases its datapath resources.
  /// Idempotent: a second call is a no-op.
  Future<void> disconnect();

  /// Whether the in-tunnel egress liveness probe currently reports
  /// the exit not forwarding (doc 62 item 5). `false` in every state
  /// other than a Connected session with dead egress.
  Future<bool> egressDead();

  /// Streams the egress verdict (doc 62 item 5), emitting the current
  /// value first so a late listener is never left without one. `true`
  /// while the exit stopped forwarding despite a live session (e.g. a
  /// drained or half-swapped exit during a fleet rollout); cleared by
  /// one successful probe or by leaving the Connected state.
  Stream<bool> egressHealth();

  /// The definitive cause the supervisor stopped on, or `None` while it is
  /// still healing (or gave up on mere retry exhaustion, which is transient
  /// and carries no cause). Read it when the state stream reaches `Failed`:
  /// the supervisor latches the cause BEFORE publishing `Failed`, so a present
  /// value there means no redial or other exit will help. A consumer surfaces
  /// it (expired subscription, device limit) and stops instead of looping
  /// `Reconnecting`.
  Future<WarrenFatalCauseDto?> fatalCause();

  /// Forwards a tunnel-side port via NAT-PMP, re-mapped automatically across
  /// reconnects. `local_target` is the local `ip:port` inbound connections are
  /// relayed to. The exit must run a NAT-PMP gateway.
  Future<WarrenForwardedPortFrb> forwardPort(
      {required MapProtoDto proto,
      required int internalPort,
      required String localTarget});

  /// Like [`Self::forward_port`], with an explicit follow policy (doc 59).
  /// `pinned_external_port` pins the external port for `KeepPortOrStay`;
  /// `None` pins the first port the exit grants. Observe what happened on
  /// each rebuild via [`WarrenForwardedPortFrb::outcomes`].
  Future<WarrenForwardedPortFrb> forwardPortWithPolicy(
      {required MapProtoDto proto,
      required int internalPort,
      required String localTarget,
      required PortFollowPolicyDto policy,
      int? pinnedExternalPort});

  /// The bound local HTTP CONNECT endpoint, if one was requested.
  Future<String?> httpEndpoint();

  /// Streams maintenance-migration events (doc 59): the drain advisory's
  /// deadline and reason plus the outcome (migrating, completed, cancelled
  /// for a pinned-port conflict). Emits the latest event first, if any, so a
  /// late listener still sees an in-flight migration.
  Stream<MigrationEventDto> migrationEvents();

  /// The password every client of the endpoints presents. A per-session
  /// secret: keep it out of logs and anything another account can read.
  Future<String> proxyPassword();

  /// The username every client of the endpoints presents (RFC 1929 on
  /// SOCKS5, `Proxy-Authorization: Basic` on HTTP CONNECT).
  Future<String> proxyUsername();

  /// The bound local SOCKS5 endpoint, for example `127.0.0.1:51234`.
  Future<String> socks5Endpoint();

  /// Streams connection-state transitions, emitting the current state first so
  /// a late listener is never left without one.
  Stream<ConnectionStateDto> states();
}

/// Why an account is banned, mirrored for Dart as a plain enum.
enum BanReasonDto {
  /// Three port-forward abuse strikes inside the sliding window.
  portForwardingAbuse,

  /// Any other revocation, and any reason this build does not know.
  other,
  ;
}

/// Lifecycle state of a connection, mirrored for Dart as a plain enum.
enum ConnectionStateDto {
  /// The initial connect attempt is in flight.
  connecting,

  /// A connection is established.
  connected,

  /// A previous attempt failed; a retry is in flight after backoff.
  reconnecting,

  /// The exit signalled a planned maintenance drain and the supervisor is
  /// proactively migrating off it (ADR 36). Distinct from failure-driven
  /// `Reconnecting` so an app can show a "switching server" hint; followed by
  /// `Connected`.
  draining,

  /// Every attempt failed; the supervisor gave up.
  failed,
  ;
}

/// Transport protocol for a forwarded port, mirrored to Dart as a plain enum.
enum MapProtoDto {
  /// TCP.
  tcp,

  /// UDP.
  udp,
  ;
}

/// A maintenance-migration lifecycle event: the drain advisory's fields plus
/// where the migration stands, richer than the bare `Draining` state.
class MigrationEventDto {
  /// Unix seconds after which the draining exit hard-closes stragglers;
  /// `u64::MAX` means a soft drain with no deadline.
  final BigInt deadlineUnixSecs;

  /// Opaque operator reason code from the drain advisory (0 = maintenance).
  final int reasonCode;

  /// Where the migration stands.
  final MigrationOutcomeDto outcome;

  const MigrationEventDto({
    required this.deadlineUnixSecs,
    required this.reasonCode,
    required this.outcome,
  });

  @override
  int get hashCode =>
      deadlineUnixSecs.hashCode ^ reasonCode.hashCode ^ outcome.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MigrationEventDto &&
          runtimeType == other.runtimeType &&
          deadlineUnixSecs == other.deadlineUnixSecs &&
          reasonCode == other.reasonCode &&
          outcome == other.outcome;
}

/// Progress of one maintenance migration, mirrored as a plain enum.
enum MigrationOutcomeDto {
  /// The drain advisory arrived; the supervisor is moving off the exit.
  migrating,

  /// The post-drain reconnect landed on the new exit.
  completed,

  /// Every candidate conflicted with a pinned port rule: the migration was
  /// cancelled and the client stays on the draining exit, keeping its port.
  cancelledPortConflict,
  ;
}

/// What happened to a forwarded port on its latest (re)establish.
class PortFollowOutcomeDto {
  /// The outcome discriminant.
  final PortFollowOutcomeKindDto kind;

  /// For `Changed`: the previous external port, absent on the first grant.
  final int? previousPort;

  /// For `Kept`/`Changed`: the granted external port. For `ConflictStayed`:
  /// the pinned port that stays requested. Absent otherwise.
  final int? port;

  /// For `NotAuthorized`: whether the refused request carried an
  /// entitlement. Absent otherwise.
  final bool? entitlementPresented;

  /// For `Banned`: why. Absent otherwise.
  final BanReasonDto? banReason;

  /// For `Banned`: when the ban lapses on its own, Unix seconds. Absent
  /// otherwise, and for a ban that does not lapse.
  final BigInt? banLapsesAtUnixSecs;

  const PortFollowOutcomeDto({
    required this.kind,
    this.previousPort,
    this.port,
    this.entitlementPresented,
    this.banReason,
    this.banLapsesAtUnixSecs,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      previousPort.hashCode ^
      port.hashCode ^
      entitlementPresented.hashCode ^
      banReason.hashCode ^
      banLapsesAtUnixSecs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PortFollowOutcomeDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          previousPort == other.previousPort &&
          port == other.port &&
          entitlementPresented == other.entitlementPresented &&
          banReason == other.banReason &&
          banLapsesAtUnixSecs == other.banLapsesAtUnixSecs;
}

/// Discriminant of a [`PortFollowOutcomeDto`]. Flattened (kind plus optional
/// ports) instead of a payload-carrying enum so the bridge stays on plain
/// generated data classes like the rest of this API.
enum PortFollowOutcomeKindDto {
  /// The previously-granted external port was re-granted on this exit.
  kept,

  /// The exit granted a different external port (first grant, server pick,
  /// or a best-effort degrade after a conflict).
  changed,

  /// A pinned port was refused and the rule did not degrade: no mapping
  /// exists this epoch, the pin stays requested for the next one.
  conflictStayed,

  /// The mapping could not be established this epoch; the supervisor keeps
  /// retrying.
  failed,

  /// The exit refused the mapping as not authorized: it presented no port
  /// entitlement, or one the exit would not spend (warren-core doc 105). The
  /// supervisor keeps retrying.
  notAuthorized,

  /// The account is banned, so the issuer refuses its port entitlements and
  /// every enforcing exit refuses its mappings. The supervisor keeps
  /// retrying, which a lifted ban answers.
  banned,
  ;
}

/// How a forwarded port follows the client across reconnects and maintenance
/// migrations, mirrored for Dart as a plain enum (doc 59).
enum PortFollowPolicyDto {
  /// Re-suggest the last granted external port; on a conflict degrade once to
  /// a server-assigned port instead of failing (the default).
  followBestEffort,

  /// Never degrade silently: on a conflict the mapping stays unset for the
  /// epoch and the pin is re-requested on the next one.
  keepPortOrStay,

  /// No follow: every epoch asks for a fresh server-assigned port.
  disabled,
  ;
}

/// Why the supervisor stopped for good, mirrored for Dart as a plain enum.
///
/// The engine owns this classification; the bridge maps it, it never re-decides.
/// Read alongside the terminal [`ConnectionStateDto::Failed`] via
/// [`WarrenSessionFrb::fatal_cause`]: a present cause is precisely the "no redial
/// or other exit helps, tell the user" signal, so a consumer stops retrying
/// instead of looping `Reconnecting` forever. A `Failed` reached by mere retry
/// exhaustion carries NO cause (the accessor returns `None`).
enum WarrenFatalCauseDto {
  /// The identity has no active subscription, or is not in the exit allowlist.
  /// The user must provision or renew; retrying reproduces it.
  notAuthorized,

  /// The account already holds its maximum simultaneous devices.
  deviceLimit,

  /// The exit closed with the opaque policy-rejection code and no sealed cause
  /// arrived: definitive, but the specific reason is unknown to the client.
  policyRefused,
  ;
}
