// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `new`, `new`, `to_dto`, `to_engine`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<WarrenForwardedPortFrb>>
abstract class WarrenForwardedPortFrb implements RustOpaqueInterface {
  /// The current external port remote peers reach the app on, or `None` while
  /// the tunnel is down or before the first mapping is granted.
  Future<int?> externalPort();

  /// Streams external-port changes (re-mappings across reconnects), emitting
  /// the current value first so a late listener always gets one.
  Stream<int?> externalPorts();

  /// The local internal port being forwarded.
  Future<int> internalPort();

  /// Tears the forward down. Idempotent: a second call is a no-op.
  Future<void> shutdown();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<WarrenSessionFrb>>
abstract class WarrenSessionFrb implements RustOpaqueInterface {
  /// Tears the connection down and releases its datapath resources.
  /// Idempotent: a second call is a no-op.
  Future<void> disconnect();

  /// Forwards a tunnel-side port via NAT-PMP, re-mapped automatically across
  /// reconnects. `local_target` is the local `ip:port` inbound connections are
  /// relayed to. The exit must run a NAT-PMP gateway.
  Future<WarrenForwardedPortFrb> forwardPort(
      {required MapProtoDto proto,
      required int internalPort,
      required String localTarget});

  /// The bound local HTTP CONNECT endpoint, if one was requested.
  Future<String?> httpEndpoint();

  /// The bound local SOCKS5 endpoint, for example `127.0.0.1:51234`.
  Future<String> socks5Endpoint();

  /// Streams connection-state transitions, emitting the current state first so
  /// a late listener is never left without one.
  Stream<ConnectionStateDto> states();
}

/// Lifecycle state of a connection, mirrored for Dart as a plain enum.
enum ConnectionStateDto {
  /// The initial connect attempt is in flight.
  connecting,

  /// A connection is established.
  connected,

  /// A previous attempt failed; a retry is in flight after backoff.
  reconnecting,

  /// The exit signalled a planned maintenance drain and the supervisor is
  /// proactively migrating off it (ADR 36). Distinct from failure-driven
  /// `Reconnecting` so an app can show a "switching server" hint; followed by
  /// `Connected`.
  draining,

  /// Every attempt failed; the supervisor gave up.
  failed,
  ;
}

/// Transport protocol for a forwarded port, mirrored to Dart as a plain enum.
enum MapProtoDto {
  /// TCP.
  tcp,

  /// UDP.
  udp,
  ;
}
