// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';

/// Generates a fresh 12-word BIP39 mnemonic.
///
/// The returned string is secret; the caller (Dart) must persist it through the
/// platform secure store and drop its reference.
Future<String> generateMnemonic() =>
    WarrenRustBridge.instance.api.crateApiIdentityGenerateMnemonic();

/// Derives the SS58 `wb...` address from a mnemonic.
///
/// Returns a redacted error if the mnemonic is malformed (no secret material is
/// included in the message).
Future<String> addressFromMnemonic({required String mnemonic}) =>
    WarrenRustBridge.instance.api
        .crateApiIdentityAddressFromMnemonic(mnemonic: mnemonic);

/// Encodes a 32-byte public key (hex) to its SS58 `wb...` address.
Future<String> ss58Encode({required String publicKeyHex}) =>
    WarrenRustBridge.instance.api
        .crateApiIdentitySs58Encode(publicKeyHex: publicKeyHex);

/// Decodes an SS58 `wb...` address back to its public key hex.
Future<String> ss58Decode({required String address}) =>
    WarrenRustBridge.instance.api.crateApiIdentitySs58Decode(address: address);

/// Signs a Warren API request deterministically from a 32-byte seed.
///
/// Low-level conformance and utility surface: production signing happens inside
/// the engine client, but this primitive replays the shared `request_signature`
/// golden vectors across the bridge, pinning the wire format and the binary body
/// marshalling. `seed_hex` is 32 bytes (64 hex chars); `nonce_hex` is 16 bytes
/// (32 hex chars). Errors are redacted: no seed or signature is echoed.
Future<SignedRequest> signRequest(
        {required String seedHex,
        required String method,
        required String path,
        required List<int> body,
        required BigInt timestamp,
        required String nonceHex}) =>
    WarrenRustBridge.instance.api.crateApiIdentitySignRequest(
        seedHex: seedHex,
        method: method,
        path: path,
        body: body,
        timestamp: timestamp,
        nonceHex: nonceHex);

/// Authentication material for a signed Warren API request.
///
/// Mirrors the engine's `RequestSignature` as a plain, bridge-friendly struct so
/// flutter_rust_bridge can marshal it to a Dart value.
class SignedRequest {
  /// The signer's SS58 `wb...` address.
  final String pubkeySs58;

  /// The 64-byte Ed25519 signature, hex-encoded.
  final String signatureHex;

  /// The request timestamp echoed back, in seconds.
  final BigInt timestamp;

  /// The 16-byte nonce echoed back, hex-encoded.
  final String nonceHex;

  const SignedRequest({
    required this.pubkeySs58,
    required this.signatureHex,
    required this.timestamp,
    required this.nonceHex,
  });

  @override
  int get hashCode =>
      pubkeySs58.hashCode ^
      signatureHex.hashCode ^
      timestamp.hashCode ^
      nonceHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SignedRequest &&
          runtimeType == other.runtimeType &&
          pubkeySs58 == other.pubkeySs58 &&
          signatureHex == other.signatureHex &&
          timestamp == other.timestamp &&
          nonceHex == other.nonceHex;
}
