// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/client.dart';
import 'api/datapath.dart';
import 'api/error.dart';
import 'api/identity.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class WarrenRustBridge extends BaseEntrypoint<WarrenRustBridgeApi,
    WarrenRustBridgeApiImpl, WarrenRustBridgeWire> {
  @internal
  static final instance = WarrenRustBridge._();

  WarrenRustBridge._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    WarrenRustBridgeApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required WarrenRustBridgeApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<WarrenRustBridgeApiImpl, WarrenRustBridgeWire>
      get apiImplConstructor => WarrenRustBridgeApiImpl.new;

  @override
  WireConstructor<WarrenRustBridgeWire> get wireConstructor =>
      WarrenRustBridgeWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 40866547;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'warren_sdk_frb',
    ioDirectory: '../../native/warren_sdk_frb/target/release/',
    webPrefix: 'pkg/',
    wasmBindgenName: 'wasm_bindgen',
  );
}

abstract class WarrenRustBridgeApi extends BaseApi {
  Future<String> crateApiClientWarrenClientFrbAddress(
      {required WarrenClientFrb that});

  Future<TunnelCheckDto> crateApiClientWarrenClientFrbCheck(
      {required WarrenClientFrb that});

  Future<WarrenSessionFrb> crateApiClientWarrenClientFrbConnectProxy(
      {required WarrenClientFrb that,
      required String exitPubkeyHex,
      required List<String> failoverExitPubkeysHex,
      required String socks5Listen,
      String? httpListen,
      String? dnsServer});

  Future<WarrenClientFrb> crateApiClientWarrenClientFrbCreate(
      {required String mnemonic,
      required String apiBase,
      required List<String> apiAlternativeHosts,
      required String serverPubkeyPin,
      String? multihopRootPin,
      required bool daita,
      String? daitaMachine,
      required bool requestIpv6,
      String? stateDir});

  Future<void> crateApiClientWarrenClientFrbDeleteAccount(
      {required WarrenClientFrb that});

  Future<List<ExitInfoDto>> crateApiClientWarrenClientFrbListExits(
      {required WarrenClientFrb that});

  Future<BigInt> crateApiClientWarrenClientFrbRedeemVoucher(
      {required WarrenClientFrb that, required String secret});

  Future<BigInt> crateApiClientWarrenClientFrbSubscriptionExpiry(
      {required WarrenClientFrb that});

  Future<int?> crateApiDatapathWarrenForwardedPortFrbExternalPort(
      {required WarrenForwardedPortFrb that});

  Stream<int?> crateApiDatapathWarrenForwardedPortFrbExternalPorts(
      {required WarrenForwardedPortFrb that});

  Future<int> crateApiDatapathWarrenForwardedPortFrbInternalPort(
      {required WarrenForwardedPortFrb that});

  Stream<PortFollowOutcomeDto> crateApiDatapathWarrenForwardedPortFrbOutcomes(
      {required WarrenForwardedPortFrb that});

  Future<void> crateApiDatapathWarrenForwardedPortFrbShutdown(
      {required WarrenForwardedPortFrb that});

  Future<void> crateApiDatapathWarrenSessionFrbDisconnect(
      {required WarrenSessionFrb that});

  Future<bool> crateApiDatapathWarrenSessionFrbEgressDead(
      {required WarrenSessionFrb that});

  Stream<bool> crateApiDatapathWarrenSessionFrbEgressHealth(
      {required WarrenSessionFrb that});

  Future<WarrenFatalCauseDto?> crateApiDatapathWarrenSessionFrbFatalCause(
      {required WarrenSessionFrb that});

  Future<WarrenForwardedPortFrb> crateApiDatapathWarrenSessionFrbForwardPort(
      {required WarrenSessionFrb that,
      required MapProtoDto proto,
      required int internalPort,
      required String localTarget});

  Future<WarrenForwardedPortFrb>
      crateApiDatapathWarrenSessionFrbForwardPortWithPolicy(
          {required WarrenSessionFrb that,
          required MapProtoDto proto,
          required int internalPort,
          required String localTarget,
          required PortFollowPolicyDto policy,
          int? pinnedExternalPort});

  Future<String?> crateApiDatapathWarrenSessionFrbHttpEndpoint(
      {required WarrenSessionFrb that});

  Stream<MigrationEventDto> crateApiDatapathWarrenSessionFrbMigrationEvents(
      {required WarrenSessionFrb that});

  Future<String> crateApiDatapathWarrenSessionFrbSocks5Endpoint(
      {required WarrenSessionFrb that});

  Stream<ConnectionStateDto> crateApiDatapathWarrenSessionFrbStates(
      {required WarrenSessionFrb that});

  Future<String> crateApiIdentityAddressFromMnemonic(
      {required String mnemonic});

  Future<String> crateApiIdentityGenerateMnemonic();

  Future<SignedRequest> crateApiIdentitySignRequest(
      {required String seedHex,
      required String method,
      required String path,
      required List<int> body,
      required BigInt timestamp,
      required String nonceHex});

  Future<String> crateApiIdentitySs58Decode({required String address});

  Future<String> crateApiIdentitySs58Encode({required String publicKeyHex});

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_WarrenClientFrb;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_WarrenClientFrb;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_WarrenClientFrbPtr;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_WarrenForwardedPortFrb;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_WarrenForwardedPortFrb;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_WarrenForwardedPortFrbPtr;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_WarrenSessionFrb;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_WarrenSessionFrb;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_WarrenSessionFrbPtr;
}

class WarrenRustBridgeApiImpl extends WarrenRustBridgeApiImplPlatform
    implements WarrenRustBridgeApi {
  WarrenRustBridgeApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateApiClientWarrenClientFrbAddress(
      {required WarrenClientFrb that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenClientFrb(
            that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiClientWarrenClientFrbAddressConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiClientWarrenClientFrbAddressConstMeta =>
      const TaskConstMeta(
        debugName: "WarrenClientFrb_address",
        argNames: ["that"],
      );

  @override
  Future<TunnelCheckDto> crateApiClientWarrenClientFrbCheck(
      {required WarrenClientFrb that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenClientFrb(
            that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_tunnel_check_dto,
        decodeErrorData: sse_decode_warren_ffi_error,
      ),
      constMeta: kCrateApiClientWarrenClientFrbCheckConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiClientWarrenClientFrbCheckConstMeta =>
      const TaskConstMeta(
        debugName: "WarrenClientFrb_check",
        argNames: ["that"],
      );

  @override
  Future<WarrenSessionFrb> crateApiClientWarrenClientFrbConnectProxy(
      {required WarrenClientFrb that,
      required String exitPubkeyHex,
      required List<String> failoverExitPubkeysHex,
      required String socks5Listen,
      String? httpListen,
      String? dnsServer}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenClientFrb(
            that, serializer);
        sse_encode_String(exitPubkeyHex, serializer);
        sse_encode_list_String(failoverExitPubkeysHex, serializer);
        sse_encode_String(socks5Listen, serializer);
        sse_encode_opt_String(httpListen, serializer);
        sse_encode_opt_String(dnsServer, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenSessionFrb,
        decodeErrorData: sse_decode_warren_ffi_error,
      ),
      constMeta: kCrateApiClientWarrenClientFrbConnectProxyConstMeta,
      argValues: [
        that,
        exitPubkeyHex,
        failoverExitPubkeysHex,
        socks5Listen,
        httpListen,
        dnsServer
      ],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiClientWarrenClientFrbConnectProxyConstMeta =>
      const TaskConstMeta(
        debugName: "WarrenClientFrb_connect_proxy",
        argNames: [
          "that",
          "exitPubkeyHex",
          "failoverExitPubkeysHex",
          "socks5Listen",
          "httpListen",
          "dnsServer"
        ],
      );

  @override
  Future<WarrenClientFrb> crateApiClientWarrenClientFrbCreate(
      {required String mnemonic,
      required String apiBase,
      required List<String> apiAlternativeHosts,
      required String serverPubkeyPin,
      String? multihopRootPin,
      required bool daita,
      String? daitaMachine,
      required bool requestIpv6,
      String? stateDir}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(mnemonic, serializer);
        sse_encode_String(apiBase, serializer);
        sse_encode_list_String(apiAlternativeHosts, serializer);
        sse_encode_String(serverPubkeyPin, serializer);
        sse_encode_opt_String(multihopRootPin, serializer);
        sse_encode_bool(daita, serializer);
        sse_encode_opt_String(daitaMachine, serializer);
        sse_encode_bool(requestIpv6, serializer);
        sse_encode_opt_String(stateDir, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenClientFrb,
        decodeErrorData: sse_decode_warren_ffi_error,
      ),
      constMeta: kCrateApiClientWarrenClientFrbCreateConstMeta,
      argValues: [
        mnemonic,
        apiBase,
        apiAlternativeHosts,
        serverPubkeyPin,
        multihopRootPin,
        daita,
        daitaMachine,
        requestIpv6,
        stateDir
      ],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiClientWarrenClientFrbCreateConstMeta =>
      const TaskConstMeta(
        debugName: "WarrenClientFrb_create",
        argNames: [
          "mnemonic",
          "apiBase",
          "apiAlternativeHosts",
          "serverPubkeyPin",
          "multihopRootPin",
          "daita",
          "daitaMachine",
          "requestIpv6",
          "stateDir"
        ],
      );

  @override
  Future<void> crateApiClientWarrenClientFrbDeleteAccount(
      {required WarrenClientFrb that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenClientFrb(
            that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_warren_ffi_error,
      ),
      constMeta: kCrateApiClientWarrenClientFrbDeleteAccountConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiClientWarrenClientFrbDeleteAccountConstMeta =>
      const TaskConstMeta(
        debugName: "WarrenClientFrb_delete_account",
        argNames: ["that"],
      );

  @override
  Future<List<ExitInfoDto>> crateApiClientWarrenClientFrbListExits(
      {required WarrenClientFrb that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenClientFrb(
            that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_exit_info_dto,
        decodeErrorData: sse_decode_warren_ffi_error,
      ),
      constMeta: kCrateApiClientWarrenClientFrbListExitsConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiClientWarrenClientFrbListExitsConstMeta =>
      const TaskConstMeta(
        debugName: "WarrenClientFrb_list_exits",
        argNames: ["that"],
      );

  @override
  Future<BigInt> crateApiClientWarrenClientFrbRedeemVoucher(
      {required WarrenClientFrb that, required String secret}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenClientFrb(
            that, serializer);
        sse_encode_String(secret, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_u_64,
        decodeErrorData: sse_decode_warren_ffi_error,
      ),
      constMeta: kCrateApiClientWarrenClientFrbRedeemVoucherConstMeta,
      argValues: [that, secret],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiClientWarrenClientFrbRedeemVoucherConstMeta =>
      const TaskConstMeta(
        debugName: "WarrenClientFrb_redeem_voucher",
        argNames: ["that", "secret"],
      );

  @override
  Future<BigInt> crateApiClientWarrenClientFrbSubscriptionExpiry(
      {required WarrenClientFrb that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenClientFrb(
            that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_u_64,
        decodeErrorData: sse_decode_warren_ffi_error,
      ),
      constMeta: kCrateApiClientWarrenClientFrbSubscriptionExpiryConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiClientWarrenClientFrbSubscriptionExpiryConstMeta =>
      const TaskConstMeta(
        debugName: "WarrenClientFrb_subscription_expiry",
        argNames: ["that"],
      );

  @override
  Future<int?> crateApiDatapathWarrenForwardedPortFrbExternalPort(
      {required WarrenForwardedPortFrb that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenForwardedPortFrb(
            that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_box_autoadd_u_16,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiDatapathWarrenForwardedPortFrbExternalPortConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiDatapathWarrenForwardedPortFrbExternalPortConstMeta =>
          const TaskConstMeta(
            debugName: "WarrenForwardedPortFrb_external_port",
            argNames: ["that"],
          );

  @override
  Stream<int?> crateApiDatapathWarrenForwardedPortFrbExternalPorts(
      {required WarrenForwardedPortFrb that}) {
    final sink = RustStreamSink<int?>();
    unawaited(handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenForwardedPortFrb(
            that, serializer);
        sse_encode_StreamSink_opt_box_autoadd_u_16_Sse(sink, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 10, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiDatapathWarrenForwardedPortFrbExternalPortsConstMeta,
      argValues: [that, sink],
      apiImpl: this,
    )));
    return sink.stream;
  }

  TaskConstMeta
      get kCrateApiDatapathWarrenForwardedPortFrbExternalPortsConstMeta =>
          const TaskConstMeta(
            debugName: "WarrenForwardedPortFrb_external_ports",
            argNames: ["that", "sink"],
          );

  @override
  Future<int> crateApiDatapathWarrenForwardedPortFrbInternalPort(
      {required WarrenForwardedPortFrb that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenForwardedPortFrb(
            that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 11, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_u_16,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiDatapathWarrenForwardedPortFrbInternalPortConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiDatapathWarrenForwardedPortFrbInternalPortConstMeta =>
          const TaskConstMeta(
            debugName: "WarrenForwardedPortFrb_internal_port",
            argNames: ["that"],
          );

  @override
  Stream<PortFollowOutcomeDto> crateApiDatapathWarrenForwardedPortFrbOutcomes(
      {required WarrenForwardedPortFrb that}) {
    final sink = RustStreamSink<PortFollowOutcomeDto>();
    unawaited(handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenForwardedPortFrb(
            that, serializer);
        sse_encode_StreamSink_port_follow_outcome_dto_Sse(sink, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 12, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiDatapathWarrenForwardedPortFrbOutcomesConstMeta,
      argValues: [that, sink],
      apiImpl: this,
    )));
    return sink.stream;
  }

  TaskConstMeta get kCrateApiDatapathWarrenForwardedPortFrbOutcomesConstMeta =>
      const TaskConstMeta(
        debugName: "WarrenForwardedPortFrb_outcomes",
        argNames: ["that", "sink"],
      );

  @override
  Future<void> crateApiDatapathWarrenForwardedPortFrbShutdown(
      {required WarrenForwardedPortFrb that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenForwardedPortFrb(
            that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 13, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiDatapathWarrenForwardedPortFrbShutdownConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDatapathWarrenForwardedPortFrbShutdownConstMeta =>
      const TaskConstMeta(
        debugName: "WarrenForwardedPortFrb_shutdown",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiDatapathWarrenSessionFrbDisconnect(
      {required WarrenSessionFrb that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenSessionFrb(
            that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 14, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiDatapathWarrenSessionFrbDisconnectConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDatapathWarrenSessionFrbDisconnectConstMeta =>
      const TaskConstMeta(
        debugName: "WarrenSessionFrb_disconnect",
        argNames: ["that"],
      );

  @override
  Future<bool> crateApiDatapathWarrenSessionFrbEgressDead(
      {required WarrenSessionFrb that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenSessionFrb(
            that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 15, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiDatapathWarrenSessionFrbEgressDeadConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDatapathWarrenSessionFrbEgressDeadConstMeta =>
      const TaskConstMeta(
        debugName: "WarrenSessionFrb_egress_dead",
        argNames: ["that"],
      );

  @override
  Stream<bool> crateApiDatapathWarrenSessionFrbEgressHealth(
      {required WarrenSessionFrb that}) {
    final sink = RustStreamSink<bool>();
    unawaited(handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenSessionFrb(
            that, serializer);
        sse_encode_StreamSink_bool_Sse(sink, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 16, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiDatapathWarrenSessionFrbEgressHealthConstMeta,
      argValues: [that, sink],
      apiImpl: this,
    )));
    return sink.stream;
  }

  TaskConstMeta get kCrateApiDatapathWarrenSessionFrbEgressHealthConstMeta =>
      const TaskConstMeta(
        debugName: "WarrenSessionFrb_egress_health",
        argNames: ["that", "sink"],
      );

  @override
  Future<WarrenFatalCauseDto?> crateApiDatapathWarrenSessionFrbFatalCause(
      {required WarrenSessionFrb that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenSessionFrb(
            that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 17, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_box_autoadd_warren_fatal_cause_dto,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiDatapathWarrenSessionFrbFatalCauseConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDatapathWarrenSessionFrbFatalCauseConstMeta =>
      const TaskConstMeta(
        debugName: "WarrenSessionFrb_fatal_cause",
        argNames: ["that"],
      );

  @override
  Future<WarrenForwardedPortFrb> crateApiDatapathWarrenSessionFrbForwardPort(
      {required WarrenSessionFrb that,
      required MapProtoDto proto,
      required int internalPort,
      required String localTarget}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenSessionFrb(
            that, serializer);
        sse_encode_map_proto_dto(proto, serializer);
        sse_encode_u_16(internalPort, serializer);
        sse_encode_String(localTarget, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 18, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenForwardedPortFrb,
        decodeErrorData: sse_decode_warren_ffi_error,
      ),
      constMeta: kCrateApiDatapathWarrenSessionFrbForwardPortConstMeta,
      argValues: [that, proto, internalPort, localTarget],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDatapathWarrenSessionFrbForwardPortConstMeta =>
      const TaskConstMeta(
        debugName: "WarrenSessionFrb_forward_port",
        argNames: ["that", "proto", "internalPort", "localTarget"],
      );

  @override
  Future<WarrenForwardedPortFrb>
      crateApiDatapathWarrenSessionFrbForwardPortWithPolicy(
          {required WarrenSessionFrb that,
          required MapProtoDto proto,
          required int internalPort,
          required String localTarget,
          required PortFollowPolicyDto policy,
          int? pinnedExternalPort}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenSessionFrb(
            that, serializer);
        sse_encode_map_proto_dto(proto, serializer);
        sse_encode_u_16(internalPort, serializer);
        sse_encode_String(localTarget, serializer);
        sse_encode_port_follow_policy_dto(policy, serializer);
        sse_encode_opt_box_autoadd_u_16(pinnedExternalPort, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 19, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenForwardedPortFrb,
        decodeErrorData: sse_decode_warren_ffi_error,
      ),
      constMeta:
          kCrateApiDatapathWarrenSessionFrbForwardPortWithPolicyConstMeta,
      argValues: [
        that,
        proto,
        internalPort,
        localTarget,
        policy,
        pinnedExternalPort
      ],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiDatapathWarrenSessionFrbForwardPortWithPolicyConstMeta =>
          const TaskConstMeta(
            debugName: "WarrenSessionFrb_forward_port_with_policy",
            argNames: [
              "that",
              "proto",
              "internalPort",
              "localTarget",
              "policy",
              "pinnedExternalPort"
            ],
          );

  @override
  Future<String?> crateApiDatapathWarrenSessionFrbHttpEndpoint(
      {required WarrenSessionFrb that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenSessionFrb(
            that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 20, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiDatapathWarrenSessionFrbHttpEndpointConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDatapathWarrenSessionFrbHttpEndpointConstMeta =>
      const TaskConstMeta(
        debugName: "WarrenSessionFrb_http_endpoint",
        argNames: ["that"],
      );

  @override
  Stream<MigrationEventDto> crateApiDatapathWarrenSessionFrbMigrationEvents(
      {required WarrenSessionFrb that}) {
    final sink = RustStreamSink<MigrationEventDto>();
    unawaited(handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenSessionFrb(
            that, serializer);
        sse_encode_StreamSink_migration_event_dto_Sse(sink, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 21, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiDatapathWarrenSessionFrbMigrationEventsConstMeta,
      argValues: [that, sink],
      apiImpl: this,
    )));
    return sink.stream;
  }

  TaskConstMeta get kCrateApiDatapathWarrenSessionFrbMigrationEventsConstMeta =>
      const TaskConstMeta(
        debugName: "WarrenSessionFrb_migration_events",
        argNames: ["that", "sink"],
      );

  @override
  Future<String> crateApiDatapathWarrenSessionFrbSocks5Endpoint(
      {required WarrenSessionFrb that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenSessionFrb(
            that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 22, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiDatapathWarrenSessionFrbSocks5EndpointConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDatapathWarrenSessionFrbSocks5EndpointConstMeta =>
      const TaskConstMeta(
        debugName: "WarrenSessionFrb_socks5_endpoint",
        argNames: ["that"],
      );

  @override
  Stream<ConnectionStateDto> crateApiDatapathWarrenSessionFrbStates(
      {required WarrenSessionFrb that}) {
    final sink = RustStreamSink<ConnectionStateDto>();
    unawaited(handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenSessionFrb(
            that, serializer);
        sse_encode_StreamSink_connection_state_dto_Sse(sink, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 23, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiDatapathWarrenSessionFrbStatesConstMeta,
      argValues: [that, sink],
      apiImpl: this,
    )));
    return sink.stream;
  }

  TaskConstMeta get kCrateApiDatapathWarrenSessionFrbStatesConstMeta =>
      const TaskConstMeta(
        debugName: "WarrenSessionFrb_states",
        argNames: ["that", "sink"],
      );

  @override
  Future<String> crateApiIdentityAddressFromMnemonic(
      {required String mnemonic}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(mnemonic, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 24, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiIdentityAddressFromMnemonicConstMeta,
      argValues: [mnemonic],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiIdentityAddressFromMnemonicConstMeta =>
      const TaskConstMeta(
        debugName: "address_from_mnemonic",
        argNames: ["mnemonic"],
      );

  @override
  Future<String> crateApiIdentityGenerateMnemonic() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 25, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiIdentityGenerateMnemonicConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiIdentityGenerateMnemonicConstMeta =>
      const TaskConstMeta(
        debugName: "generate_mnemonic",
        argNames: [],
      );

  @override
  Future<SignedRequest> crateApiIdentitySignRequest(
      {required String seedHex,
      required String method,
      required String path,
      required List<int> body,
      required BigInt timestamp,
      required String nonceHex}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(seedHex, serializer);
        sse_encode_String(method, serializer);
        sse_encode_String(path, serializer);
        sse_encode_list_prim_u_8_loose(body, serializer);
        sse_encode_u_64(timestamp, serializer);
        sse_encode_String(nonceHex, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 26, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_signed_request,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiIdentitySignRequestConstMeta,
      argValues: [seedHex, method, path, body, timestamp, nonceHex],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiIdentitySignRequestConstMeta =>
      const TaskConstMeta(
        debugName: "sign_request",
        argNames: [
          "seedHex",
          "method",
          "path",
          "body",
          "timestamp",
          "nonceHex"
        ],
      );

  @override
  Future<String> crateApiIdentitySs58Decode({required String address}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(address, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 27, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiIdentitySs58DecodeConstMeta,
      argValues: [address],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiIdentitySs58DecodeConstMeta => const TaskConstMeta(
        debugName: "ss58_decode",
        argNames: ["address"],
      );

  @override
  Future<String> crateApiIdentitySs58Encode({required String publicKeyHex}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(publicKeyHex, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 28, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiIdentitySs58EncodeConstMeta,
      argValues: [publicKeyHex],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiIdentitySs58EncodeConstMeta => const TaskConstMeta(
        debugName: "ss58_encode",
        argNames: ["publicKeyHex"],
      );

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_WarrenClientFrb => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenClientFrb;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_WarrenClientFrb => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenClientFrb;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_WarrenForwardedPortFrb => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenForwardedPortFrb;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_WarrenForwardedPortFrb => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenForwardedPortFrb;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_WarrenSessionFrb => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenSessionFrb;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_WarrenSessionFrb => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenSessionFrb;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  WarrenClientFrb
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenClientFrb(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return WarrenClientFrbImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  WarrenForwardedPortFrb
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenForwardedPortFrb(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return WarrenForwardedPortFrbImpl.frbInternalDcoDecode(
        raw as List<dynamic>);
  }

  @protected
  WarrenSessionFrb
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenSessionFrb(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return WarrenSessionFrbImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  WarrenClientFrb
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenClientFrb(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return WarrenClientFrbImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  WarrenForwardedPortFrb
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenForwardedPortFrb(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return WarrenForwardedPortFrbImpl.frbInternalDcoDecode(
        raw as List<dynamic>);
  }

  @protected
  WarrenSessionFrb
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenSessionFrb(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return WarrenSessionFrbImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  WarrenClientFrb
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenClientFrb(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return WarrenClientFrbImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  WarrenForwardedPortFrb
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenForwardedPortFrb(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return WarrenForwardedPortFrbImpl.frbInternalDcoDecode(
        raw as List<dynamic>);
  }

  @protected
  WarrenSessionFrb
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenSessionFrb(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return WarrenSessionFrbImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RustStreamSink<bool> dco_decode_StreamSink_bool_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<ConnectionStateDto>
      dco_decode_StreamSink_connection_state_dto_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<MigrationEventDto>
      dco_decode_StreamSink_migration_event_dto_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<int?> dco_decode_StreamSink_opt_box_autoadd_u_16_Sse(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<PortFollowOutcomeDto>
      dco_decode_StreamSink_port_follow_outcome_dto_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  int dco_decode_box_autoadd_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  WarrenFatalCauseDto dco_decode_box_autoadd_warren_fatal_cause_dto(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_warren_fatal_cause_dto(raw);
  }

  @protected
  ConnectionStateDto dco_decode_connection_state_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ConnectionStateDto.values[raw as int];
  }

  @protected
  ExitInfoDto dco_decode_exit_info_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return ExitInfoDto(
      id: dco_decode_String(arr[0]),
      country: dco_decode_String(arr[1]),
      city: dco_decode_String(arr[2]),
      supportsIpv6: dco_decode_bool(arr[3]),
      coverDomain: dco_decode_opt_String(arr[4]),
      weight: dco_decode_u_64(arr[5]),
      isActive: dco_decode_bool(arr[6]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<ExitInfoDto> dco_decode_list_exit_info_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_exit_info_dto).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  MapProtoDto dco_decode_map_proto_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MapProtoDto.values[raw as int];
  }

  @protected
  MigrationEventDto dco_decode_migration_event_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return MigrationEventDto(
      deadlineUnixSecs: dco_decode_u_64(arr[0]),
      reasonCode: dco_decode_u_8(arr[1]),
      outcome: dco_decode_migration_outcome_dto(arr[2]),
    );
  }

  @protected
  MigrationOutcomeDto dco_decode_migration_outcome_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MigrationOutcomeDto.values[raw as int];
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_16(raw);
  }

  @protected
  WarrenFatalCauseDto? dco_decode_opt_box_autoadd_warren_fatal_cause_dto(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_warren_fatal_cause_dto(raw);
  }

  @protected
  PortFollowOutcomeDto dco_decode_port_follow_outcome_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return PortFollowOutcomeDto(
      kind: dco_decode_port_follow_outcome_kind_dto(arr[0]),
      previousPort: dco_decode_opt_box_autoadd_u_16(arr[1]),
      port: dco_decode_opt_box_autoadd_u_16(arr[2]),
    );
  }

  @protected
  PortFollowOutcomeKindDto dco_decode_port_follow_outcome_kind_dto(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PortFollowOutcomeKindDto.values[raw as int];
  }

  @protected
  PortFollowPolicyDto dco_decode_port_follow_policy_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PortFollowPolicyDto.values[raw as int];
  }

  @protected
  SignedRequest dco_decode_signed_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return SignedRequest(
      pubkeySs58: dco_decode_String(arr[0]),
      signatureHex: dco_decode_String(arr[1]),
      timestamp: dco_decode_u_64(arr[2]),
      nonceHex: dco_decode_String(arr[3]),
    );
  }

  @protected
  TunnelCheckDto dco_decode_tunnel_check_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return TunnelCheckDto(
      ip: dco_decode_String(arr[0]),
      isExit: dco_decode_bool(arr[1]),
      country: dco_decode_opt_String(arr[2]),
      city: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  WarrenErrorKind dco_decode_warren_error_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return WarrenErrorKind.values[raw as int];
  }

  @protected
  WarrenFatalCauseDto dco_decode_warren_fatal_cause_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return WarrenFatalCauseDto.values[raw as int];
  }

  @protected
  WarrenFfiError dco_decode_warren_ffi_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return WarrenFfiError(
      kind: dco_decode_warren_error_kind(arr[0]),
      message: dco_decode_String(arr[1]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  WarrenClientFrb
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenClientFrb(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return WarrenClientFrbImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  WarrenForwardedPortFrb
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenForwardedPortFrb(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return WarrenForwardedPortFrbImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  WarrenSessionFrb
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenSessionFrb(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return WarrenSessionFrbImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  WarrenClientFrb
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenClientFrb(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return WarrenClientFrbImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  WarrenForwardedPortFrb
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenForwardedPortFrb(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return WarrenForwardedPortFrbImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  WarrenSessionFrb
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenSessionFrb(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return WarrenSessionFrbImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  WarrenClientFrb
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenClientFrb(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return WarrenClientFrbImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  WarrenForwardedPortFrb
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenForwardedPortFrb(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return WarrenForwardedPortFrbImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  WarrenSessionFrb
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenSessionFrb(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return WarrenSessionFrbImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  RustStreamSink<bool> sse_decode_StreamSink_bool_Sse(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<ConnectionStateDto>
      sse_decode_StreamSink_connection_state_dto_Sse(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<MigrationEventDto>
      sse_decode_StreamSink_migration_event_dto_Sse(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<int?> sse_decode_StreamSink_opt_box_autoadd_u_16_Sse(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<PortFollowOutcomeDto>
      sse_decode_StreamSink_port_follow_outcome_dto_Sse(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  int sse_decode_box_autoadd_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_16(deserializer));
  }

  @protected
  WarrenFatalCauseDto sse_decode_box_autoadd_warren_fatal_cause_dto(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_warren_fatal_cause_dto(deserializer));
  }

  @protected
  ConnectionStateDto sse_decode_connection_state_dto(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ConnectionStateDto.values[inner];
  }

  @protected
  ExitInfoDto sse_decode_exit_info_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_country = sse_decode_String(deserializer);
    var var_city = sse_decode_String(deserializer);
    var var_supportsIpv6 = sse_decode_bool(deserializer);
    var var_coverDomain = sse_decode_opt_String(deserializer);
    var var_weight = sse_decode_u_64(deserializer);
    var var_isActive = sse_decode_bool(deserializer);
    return ExitInfoDto(
        id: var_id,
        country: var_country,
        city: var_city,
        supportsIpv6: var_supportsIpv6,
        coverDomain: var_coverDomain,
        weight: var_weight,
        isActive: var_isActive);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<ExitInfoDto> sse_decode_list_exit_info_dto(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ExitInfoDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_exit_info_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  MapProtoDto sse_decode_map_proto_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return MapProtoDto.values[inner];
  }

  @protected
  MigrationEventDto sse_decode_migration_event_dto(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_deadlineUnixSecs = sse_decode_u_64(deserializer);
    var var_reasonCode = sse_decode_u_8(deserializer);
    var var_outcome = sse_decode_migration_outcome_dto(deserializer);
    return MigrationEventDto(
        deadlineUnixSecs: var_deadlineUnixSecs,
        reasonCode: var_reasonCode,
        outcome: var_outcome);
  }

  @protected
  MigrationOutcomeDto sse_decode_migration_outcome_dto(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return MigrationOutcomeDto.values[inner];
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_16(deserializer));
    } else {
      return null;
    }
  }

  @protected
  WarrenFatalCauseDto? sse_decode_opt_box_autoadd_warren_fatal_cause_dto(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_warren_fatal_cause_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PortFollowOutcomeDto sse_decode_port_follow_outcome_dto(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_port_follow_outcome_kind_dto(deserializer);
    var var_previousPort = sse_decode_opt_box_autoadd_u_16(deserializer);
    var var_port = sse_decode_opt_box_autoadd_u_16(deserializer);
    return PortFollowOutcomeDto(
        kind: var_kind, previousPort: var_previousPort, port: var_port);
  }

  @protected
  PortFollowOutcomeKindDto sse_decode_port_follow_outcome_kind_dto(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return PortFollowOutcomeKindDto.values[inner];
  }

  @protected
  PortFollowPolicyDto sse_decode_port_follow_policy_dto(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return PortFollowPolicyDto.values[inner];
  }

  @protected
  SignedRequest sse_decode_signed_request(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_pubkeySs58 = sse_decode_String(deserializer);
    var var_signatureHex = sse_decode_String(deserializer);
    var var_timestamp = sse_decode_u_64(deserializer);
    var var_nonceHex = sse_decode_String(deserializer);
    return SignedRequest(
        pubkeySs58: var_pubkeySs58,
        signatureHex: var_signatureHex,
        timestamp: var_timestamp,
        nonceHex: var_nonceHex);
  }

  @protected
  TunnelCheckDto sse_decode_tunnel_check_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ip = sse_decode_String(deserializer);
    var var_isExit = sse_decode_bool(deserializer);
    var var_country = sse_decode_opt_String(deserializer);
    var var_city = sse_decode_opt_String(deserializer);
    return TunnelCheckDto(
        ip: var_ip, isExit: var_isExit, country: var_country, city: var_city);
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  WarrenErrorKind sse_decode_warren_error_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return WarrenErrorKind.values[inner];
  }

  @protected
  WarrenFatalCauseDto sse_decode_warren_fatal_cause_dto(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return WarrenFatalCauseDto.values[inner];
  }

  @protected
  WarrenFfiError sse_decode_warren_ffi_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_warren_error_kind(deserializer);
    var var_message = sse_decode_String(deserializer);
    return WarrenFfiError(kind: var_kind, message: var_message);
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenClientFrb(
          WarrenClientFrb self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as WarrenClientFrbImpl).frbInternalSseEncode(move: true),
        serializer);
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenForwardedPortFrb(
          WarrenForwardedPortFrb self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as WarrenForwardedPortFrbImpl).frbInternalSseEncode(move: true),
        serializer);
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenSessionFrb(
          WarrenSessionFrb self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as WarrenSessionFrbImpl).frbInternalSseEncode(move: true),
        serializer);
  }

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenClientFrb(
          WarrenClientFrb self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as WarrenClientFrbImpl).frbInternalSseEncode(move: false),
        serializer);
  }

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenForwardedPortFrb(
          WarrenForwardedPortFrb self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as WarrenForwardedPortFrbImpl).frbInternalSseEncode(move: false),
        serializer);
  }

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenSessionFrb(
          WarrenSessionFrb self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as WarrenSessionFrbImpl).frbInternalSseEncode(move: false),
        serializer);
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenClientFrb(
          WarrenClientFrb self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as WarrenClientFrbImpl).frbInternalSseEncode(move: null),
        serializer);
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenForwardedPortFrb(
          WarrenForwardedPortFrb self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as WarrenForwardedPortFrbImpl).frbInternalSseEncode(move: null),
        serializer);
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenSessionFrb(
          WarrenSessionFrb self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as WarrenSessionFrbImpl).frbInternalSseEncode(move: null),
        serializer);
  }

  @protected
  void sse_encode_StreamSink_bool_Sse(
      RustStreamSink<bool> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
        self.setupAndSerialize(
            codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        )),
        serializer);
  }

  @protected
  void sse_encode_StreamSink_connection_state_dto_Sse(
      RustStreamSink<ConnectionStateDto> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
        self.setupAndSerialize(
            codec: SseCodec(
          decodeSuccessData: sse_decode_connection_state_dto,
          decodeErrorData: sse_decode_AnyhowException,
        )),
        serializer);
  }

  @protected
  void sse_encode_StreamSink_migration_event_dto_Sse(
      RustStreamSink<MigrationEventDto> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
        self.setupAndSerialize(
            codec: SseCodec(
          decodeSuccessData: sse_decode_migration_event_dto,
          decodeErrorData: sse_decode_AnyhowException,
        )),
        serializer);
  }

  @protected
  void sse_encode_StreamSink_opt_box_autoadd_u_16_Sse(
      RustStreamSink<int?> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
        self.setupAndSerialize(
            codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_u_16,
          decodeErrorData: sse_decode_AnyhowException,
        )),
        serializer);
  }

  @protected
  void sse_encode_StreamSink_port_follow_outcome_dto_Sse(
      RustStreamSink<PortFollowOutcomeDto> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
        self.setupAndSerialize(
            codec: SseCodec(
          decodeSuccessData: sse_decode_port_follow_outcome_dto,
          decodeErrorData: sse_decode_AnyhowException,
        )),
        serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_16(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_warren_fatal_cause_dto(
      WarrenFatalCauseDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_warren_fatal_cause_dto(self, serializer);
  }

  @protected
  void sse_encode_connection_state_dto(
      ConnectionStateDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_exit_info_dto(ExitInfoDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.country, serializer);
    sse_encode_String(self.city, serializer);
    sse_encode_bool(self.supportsIpv6, serializer);
    sse_encode_opt_String(self.coverDomain, serializer);
    sse_encode_u_64(self.weight, serializer);
    sse_encode_bool(self.isActive, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_exit_info_dto(
      List<ExitInfoDto> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_exit_info_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
      List<int> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer
        .putUint8List(self is Uint8List ? self : Uint8List.fromList(self));
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_map_proto_dto(MapProtoDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_migration_event_dto(
      MigrationEventDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.deadlineUnixSecs, serializer);
    sse_encode_u_8(self.reasonCode, serializer);
    sse_encode_migration_outcome_dto(self.outcome, serializer);
  }

  @protected
  void sse_encode_migration_outcome_dto(
      MigrationOutcomeDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_16(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_16(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_warren_fatal_cause_dto(
      WarrenFatalCauseDto? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_warren_fatal_cause_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_port_follow_outcome_dto(
      PortFollowOutcomeDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_port_follow_outcome_kind_dto(self.kind, serializer);
    sse_encode_opt_box_autoadd_u_16(self.previousPort, serializer);
    sse_encode_opt_box_autoadd_u_16(self.port, serializer);
  }

  @protected
  void sse_encode_port_follow_outcome_kind_dto(
      PortFollowOutcomeKindDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_port_follow_policy_dto(
      PortFollowPolicyDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_signed_request(SignedRequest self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.pubkeySs58, serializer);
    sse_encode_String(self.signatureHex, serializer);
    sse_encode_u_64(self.timestamp, serializer);
    sse_encode_String(self.nonceHex, serializer);
  }

  @protected
  void sse_encode_tunnel_check_dto(
      TunnelCheckDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.ip, serializer);
    sse_encode_bool(self.isExit, serializer);
    sse_encode_opt_String(self.country, serializer);
    sse_encode_opt_String(self.city, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_warren_error_kind(
      WarrenErrorKind self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_warren_fatal_cause_dto(
      WarrenFatalCauseDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_warren_ffi_error(
      WarrenFfiError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_warren_error_kind(self.kind, serializer);
    sse_encode_String(self.message, serializer);
  }
}

@sealed
class WarrenClientFrbImpl extends RustOpaque implements WarrenClientFrb {
  // Not to be used by end users
  WarrenClientFrbImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  WarrenClientFrbImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: WarrenRustBridge
        .instance.api.rust_arc_increment_strong_count_WarrenClientFrb,
    rustArcDecrementStrongCount: WarrenRustBridge
        .instance.api.rust_arc_decrement_strong_count_WarrenClientFrb,
    rustArcDecrementStrongCountPtr: WarrenRustBridge
        .instance.api.rust_arc_decrement_strong_count_WarrenClientFrbPtr,
  );

  /// The SS58 `wb...` address of the bound identity.
  Future<String> address() =>
      WarrenRustBridge.instance.api.crateApiClientWarrenClientFrbAddress(
        that: this,
      );

  /// The account server's view of this connection (signed `GET /v1/check`):
  /// whether traffic egresses from a registered Warren exit, and which one.
  /// Confirms a tunnel end-to-end against the backend rather than a third-party
  /// IP echo.
  Future<TunnelCheckDto> check() =>
      WarrenRustBridge.instance.api.crateApiClientWarrenClientFrbCheck(
        that: this,
      );

  /// Opens a self-healing multihop proxy to the exit whose Ed25519 identity is
  /// `exit_pubkey_hex` (the `id` from [`list_exits`]), binding the local
  /// listeners. Proxy mode always uses multihop, which real exits require.
  ///
  /// When `failover_exit_pubkeys_hex` is non-empty the datapath runs over the
  /// prioritized list `[exit_pubkey_hex, ..failover]`: it sticks with the first
  /// exit that connects and only rotates to the next candidate when the current
  /// one fails to (re)establish, so one broken exit no longer wedges the session.
  ///
  /// Connect failures after this returns surface as connection state on the
  /// session, not as an error here.
  Future<WarrenSessionFrb> connectProxy(
          {required String exitPubkeyHex,
          required List<String> failoverExitPubkeysHex,
          required String socks5Listen,
          String? httpListen,
          String? dnsServer}) =>
      WarrenRustBridge.instance.api.crateApiClientWarrenClientFrbConnectProxy(
          that: this,
          exitPubkeyHex: exitPubkeyHex,
          failoverExitPubkeysHex: failoverExitPubkeysHex,
          socks5Listen: socks5Listen,
          httpListen: httpListen,
          dnsServer: dnsServer);

  /// Permanently deletes the account bound to this identity (signed
  /// `DELETE /v1/account`). App stores require an in-app account-deletion path.
  Future<void> deleteAccount() =>
      WarrenRustBridge.instance.api.crateApiClientWarrenClientFrbDeleteAccount(
        that: this,
      );

  /// Fetches and verifies the signed relay list, returning the exits.
  Future<List<ExitInfoDto>> listExits() =>
      WarrenRustBridge.instance.api.crateApiClientWarrenClientFrbListExits(
        that: this,
      );

  /// Redeems a voucher and returns the new expiry (Unix seconds).
  Future<BigInt> redeemVoucher({required String secret}) => WarrenRustBridge
      .instance.api
      .crateApiClientWarrenClientFrbRedeemVoucher(that: this, secret: secret);

  /// Unix-seconds subscription expiry (`0` means no active subscription).
  Future<BigInt> subscriptionExpiry() => WarrenRustBridge.instance.api
          .crateApiClientWarrenClientFrbSubscriptionExpiry(
        that: this,
      );
}

@sealed
class WarrenForwardedPortFrbImpl extends RustOpaque
    implements WarrenForwardedPortFrb {
  // Not to be used by end users
  WarrenForwardedPortFrbImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  WarrenForwardedPortFrbImpl.frbInternalSseDecode(
      BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: WarrenRustBridge
        .instance.api.rust_arc_increment_strong_count_WarrenForwardedPortFrb,
    rustArcDecrementStrongCount: WarrenRustBridge
        .instance.api.rust_arc_decrement_strong_count_WarrenForwardedPortFrb,
    rustArcDecrementStrongCountPtr: WarrenRustBridge
        .instance.api.rust_arc_decrement_strong_count_WarrenForwardedPortFrbPtr,
  );

  /// The current external port remote peers reach the app on, or `None` while
  /// the tunnel is down or before the first mapping is granted.
  Future<int?> externalPort() => WarrenRustBridge.instance.api
          .crateApiDatapathWarrenForwardedPortFrbExternalPort(
        that: this,
      );

  /// Streams external-port changes (re-mappings across reconnects), emitting
  /// the current value first so a late listener always gets one.
  Stream<int?> externalPorts() => WarrenRustBridge.instance.api
          .crateApiDatapathWarrenForwardedPortFrbExternalPorts(
        that: this,
      );

  /// The local internal port being forwarded.
  Future<int> internalPort() => WarrenRustBridge.instance.api
          .crateApiDatapathWarrenForwardedPortFrbInternalPort(
        that: this,
      );

  /// Streams follow outcomes (doc 59): what happened to this rule's external
  /// port on each (re)establish (kept, changed, held back by a conflict, or
  /// failed). Emits the latest outcome first, if any, so a late listener is
  /// not left without one.
  Stream<PortFollowOutcomeDto> outcomes() => WarrenRustBridge.instance.api
          .crateApiDatapathWarrenForwardedPortFrbOutcomes(
        that: this,
      );

  /// Tears the forward down. Idempotent: a second call is a no-op.
  Future<void> shutdown() => WarrenRustBridge.instance.api
          .crateApiDatapathWarrenForwardedPortFrbShutdown(
        that: this,
      );
}

@sealed
class WarrenSessionFrbImpl extends RustOpaque implements WarrenSessionFrb {
  // Not to be used by end users
  WarrenSessionFrbImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  WarrenSessionFrbImpl.frbInternalSseDecode(
      BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: WarrenRustBridge
        .instance.api.rust_arc_increment_strong_count_WarrenSessionFrb,
    rustArcDecrementStrongCount: WarrenRustBridge
        .instance.api.rust_arc_decrement_strong_count_WarrenSessionFrb,
    rustArcDecrementStrongCountPtr: WarrenRustBridge
        .instance.api.rust_arc_decrement_strong_count_WarrenSessionFrbPtr,
  );

  /// Tears the connection down and releases its datapath resources.
  /// Idempotent: a second call is a no-op.
  Future<void> disconnect() =>
      WarrenRustBridge.instance.api.crateApiDatapathWarrenSessionFrbDisconnect(
        that: this,
      );

  /// Whether the in-tunnel egress liveness probe currently reports
  /// the exit not forwarding (doc 62 item 5). `false` in every state
  /// other than a Connected session with dead egress.
  Future<bool> egressDead() =>
      WarrenRustBridge.instance.api.crateApiDatapathWarrenSessionFrbEgressDead(
        that: this,
      );

  /// Streams the egress verdict (doc 62 item 5), emitting the current
  /// value first so a late listener is never left without one. `true`
  /// while the exit stopped forwarding despite a live session (e.g. a
  /// drained or half-swapped exit during a fleet rollout); cleared by
  /// one successful probe or by leaving the Connected state.
  Stream<bool> egressHealth() => WarrenRustBridge.instance.api
          .crateApiDatapathWarrenSessionFrbEgressHealth(
        that: this,
      );

  /// The definitive cause the supervisor stopped on, or `None` while it is
  /// still healing (or gave up on mere retry exhaustion, which is transient
  /// and carries no cause). Read it when the state stream reaches `Failed`:
  /// the supervisor latches the cause BEFORE publishing `Failed`, so a present
  /// value there means no redial or other exit will help. A consumer surfaces
  /// it (expired subscription, device limit) and stops instead of looping
  /// `Reconnecting`.
  Future<WarrenFatalCauseDto?> fatalCause() =>
      WarrenRustBridge.instance.api.crateApiDatapathWarrenSessionFrbFatalCause(
        that: this,
      );

  /// Forwards a tunnel-side port via NAT-PMP, re-mapped automatically across
  /// reconnects. `local_target` is the local `ip:port` inbound connections are
  /// relayed to. The exit must run a NAT-PMP gateway.
  Future<WarrenForwardedPortFrb> forwardPort(
          {required MapProtoDto proto,
          required int internalPort,
          required String localTarget}) =>
      WarrenRustBridge.instance.api.crateApiDatapathWarrenSessionFrbForwardPort(
          that: this,
          proto: proto,
          internalPort: internalPort,
          localTarget: localTarget);

  /// Like [`Self::forward_port`], with an explicit follow policy (doc 59).
  /// `pinned_external_port` pins the external port for `KeepPortOrStay`;
  /// `None` pins the first port the exit grants. Observe what happened on
  /// each rebuild via [`WarrenForwardedPortFrb::outcomes`].
  Future<WarrenForwardedPortFrb> forwardPortWithPolicy(
          {required MapProtoDto proto,
          required int internalPort,
          required String localTarget,
          required PortFollowPolicyDto policy,
          int? pinnedExternalPort}) =>
      WarrenRustBridge.instance.api
          .crateApiDatapathWarrenSessionFrbForwardPortWithPolicy(
              that: this,
              proto: proto,
              internalPort: internalPort,
              localTarget: localTarget,
              policy: policy,
              pinnedExternalPort: pinnedExternalPort);

  /// The bound local HTTP CONNECT endpoint, if one was requested.
  Future<String?> httpEndpoint() => WarrenRustBridge.instance.api
          .crateApiDatapathWarrenSessionFrbHttpEndpoint(
        that: this,
      );

  /// Streams maintenance-migration events (doc 59): the drain advisory's
  /// deadline and reason plus the outcome (migrating, completed, cancelled
  /// for a pinned-port conflict). Emits the latest event first, if any, so a
  /// late listener still sees an in-flight migration.
  Stream<MigrationEventDto> migrationEvents() => WarrenRustBridge.instance.api
          .crateApiDatapathWarrenSessionFrbMigrationEvents(
        that: this,
      );

  /// The bound local SOCKS5 endpoint, for example `127.0.0.1:51234`.
  Future<String> socks5Endpoint() => WarrenRustBridge.instance.api
          .crateApiDatapathWarrenSessionFrbSocks5Endpoint(
        that: this,
      );

  /// Streams connection-state transitions, emitting the current state first so
  /// a late listener is never left without one.
  Stream<ConnectionStateDto> states() =>
      WarrenRustBridge.instance.api.crateApiDatapathWarrenSessionFrbStates(
        that: this,
      );
}
