// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'api/identity.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

/// Main entrypoint of the Rust API
class WarrenRustBridge extends BaseEntrypoint<WarrenRustBridgeApi,
    WarrenRustBridgeApiImpl, WarrenRustBridgeWire> {
  @internal
  static final instance = WarrenRustBridge._();

  WarrenRustBridge._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    WarrenRustBridgeApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required WarrenRustBridgeApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<WarrenRustBridgeApiImpl, WarrenRustBridgeWire>
      get apiImplConstructor => WarrenRustBridgeApiImpl.new;

  @override
  WireConstructor<WarrenRustBridgeWire> get wireConstructor =>
      WarrenRustBridgeWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 418347843;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'warren_sdk_frb',
    ioDirectory: '../../native/warren_sdk_frb/target/release/',
    webPrefix: 'pkg/',
    wasmBindgenName: 'wasm_bindgen',
  );
}

abstract class WarrenRustBridgeApi extends BaseApi {
  Future<String> crateApiIdentityAddressFromMnemonic(
      {required String mnemonic});

  Future<String> crateApiIdentityGenerateMnemonic();

  Future<SignedRequest> crateApiIdentitySignRequest(
      {required String seedHex,
      required String method,
      required String path,
      required List<int> body,
      required BigInt timestamp,
      required String nonceHex});

  Future<String> crateApiIdentitySs58Decode({required String address});

  Future<String> crateApiIdentitySs58Encode({required String publicKeyHex});
}

class WarrenRustBridgeApiImpl extends WarrenRustBridgeApiImplPlatform
    implements WarrenRustBridgeApi {
  WarrenRustBridgeApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateApiIdentityAddressFromMnemonic(
      {required String mnemonic}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mnemonic, serializer);
          pdeCallFfi(generalizedFrbRustBinding, serializer,
              funcId: 1, port: port_);
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiIdentityAddressFromMnemonicConstMeta,
        argValues: [mnemonic],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIdentityAddressFromMnemonicConstMeta =>
      const TaskConstMeta(
        debugName: "address_from_mnemonic",
        argNames: ["mnemonic"],
      );

  @override
  Future<String> crateApiIdentityGenerateMnemonic() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(generalizedFrbRustBinding, serializer,
              funcId: 2, port: port_);
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiIdentityGenerateMnemonicConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIdentityGenerateMnemonicConstMeta =>
      const TaskConstMeta(
        debugName: "generate_mnemonic",
        argNames: [],
      );

  @override
  Future<SignedRequest> crateApiIdentitySignRequest(
      {required String seedHex,
      required String method,
      required String path,
      required List<int> body,
      required BigInt timestamp,
      required String nonceHex}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(seedHex, serializer);
          sse_encode_String(method, serializer);
          sse_encode_String(path, serializer);
          sse_encode_list_prim_u_8_loose(body, serializer);
          sse_encode_u_64(timestamp, serializer);
          sse_encode_String(nonceHex, serializer);
          pdeCallFfi(generalizedFrbRustBinding, serializer,
              funcId: 3, port: port_);
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_signed_request,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiIdentitySignRequestConstMeta,
        argValues: [seedHex, method, path, body, timestamp, nonceHex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIdentitySignRequestConstMeta =>
      const TaskConstMeta(
        debugName: "sign_request",
        argNames: [
          "seedHex",
          "method",
          "path",
          "body",
          "timestamp",
          "nonceHex"
        ],
      );

  @override
  Future<String> crateApiIdentitySs58Decode({required String address}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(address, serializer);
          pdeCallFfi(generalizedFrbRustBinding, serializer,
              funcId: 4, port: port_);
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiIdentitySs58DecodeConstMeta,
        argValues: [address],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIdentitySs58DecodeConstMeta => const TaskConstMeta(
        debugName: "ss58_decode",
        argNames: ["address"],
      );

  @override
  Future<String> crateApiIdentitySs58Encode({required String publicKeyHex}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(publicKeyHex, serializer);
          pdeCallFfi(generalizedFrbRustBinding, serializer,
              funcId: 5, port: port_);
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiIdentitySs58EncodeConstMeta,
        argValues: [publicKeyHex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIdentitySs58EncodeConstMeta => const TaskConstMeta(
        debugName: "ss58_encode",
        argNames: ["publicKeyHex"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  SignedRequest dco_decode_signed_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return SignedRequest(
      pubkeySs58: dco_decode_String(arr[0]),
      signatureHex: dco_decode_String(arr[1]),
      timestamp: dco_decode_u_64(arr[2]),
      nonceHex: dco_decode_String(arr[3]),
    );
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  SignedRequest sse_decode_signed_request(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_pubkeySs58 = sse_decode_String(deserializer);
    final var_signatureHex = sse_decode_String(deserializer);
    final var_timestamp = sse_decode_u_64(deserializer);
    final var_nonceHex = sse_decode_String(deserializer);
    return SignedRequest(
        pubkeySs58: var_pubkeySs58,
        signatureHex: var_signatureHex,
        timestamp: var_timestamp,
        nonceHex: var_nonceHex);
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
      List<int> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer
        .putUint8List(self is Uint8List ? self : Uint8List.fromList(self));
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_signed_request(SignedRequest self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.pubkeySs58, serializer);
    sse_encode_String(self.signatureHex, serializer);
    sse_encode_u_64(self.timestamp, serializer);
    sse_encode_String(self.nonceHex, serializer);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}
