// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/client.dart';
import 'api/datapath.dart';
import 'api/error.dart';
import 'api/identity.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class WarrenRustBridgeApiImplPlatform
    extends BaseApiImpl<WarrenRustBridgeWire> {
  WarrenRustBridgeApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_WarrenClientFrbPtr => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenClientFrb;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_WarrenForwardedPortFrbPtr => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenForwardedPortFrb;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_WarrenSessionFrbPtr => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenSessionFrb;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  WarrenClientFrb
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenClientFrb(
          dynamic raw);

  @protected
  WarrenForwardedPortFrb
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenForwardedPortFrb(
          dynamic raw);

  @protected
  WarrenSessionFrb
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenSessionFrb(
          dynamic raw);

  @protected
  WarrenClientFrb
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenClientFrb(
          dynamic raw);

  @protected
  WarrenForwardedPortFrb
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenForwardedPortFrb(
          dynamic raw);

  @protected
  WarrenSessionFrb
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenSessionFrb(
          dynamic raw);

  @protected
  WarrenClientFrb
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenClientFrb(
          dynamic raw);

  @protected
  WarrenForwardedPortFrb
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenForwardedPortFrb(
          dynamic raw);

  @protected
  WarrenSessionFrb
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenSessionFrb(
          dynamic raw);

  @protected
  RustStreamSink<bool> dco_decode_StreamSink_bool_Sse(dynamic raw);

  @protected
  RustStreamSink<ConnectionStateDto>
      dco_decode_StreamSink_connection_state_dto_Sse(dynamic raw);

  @protected
  RustStreamSink<MigrationEventDto>
      dco_decode_StreamSink_migration_event_dto_Sse(dynamic raw);

  @protected
  RustStreamSink<int?> dco_decode_StreamSink_opt_box_autoadd_u_16_Sse(
      dynamic raw);

  @protected
  RustStreamSink<PortFollowOutcomeDto>
      dco_decode_StreamSink_port_follow_outcome_dto_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_16(dynamic raw);

  @protected
  WarrenFatalCauseDto dco_decode_box_autoadd_warren_fatal_cause_dto(
      dynamic raw);

  @protected
  ConnectionStateDto dco_decode_connection_state_dto(dynamic raw);

  @protected
  ExitInfoDto dco_decode_exit_info_dto(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<ExitInfoDto> dco_decode_list_exit_info_dto(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  MapProtoDto dco_decode_map_proto_dto(dynamic raw);

  @protected
  MigrationEventDto dco_decode_migration_event_dto(dynamic raw);

  @protected
  MigrationOutcomeDto dco_decode_migration_outcome_dto(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_16(dynamic raw);

  @protected
  WarrenFatalCauseDto? dco_decode_opt_box_autoadd_warren_fatal_cause_dto(
      dynamic raw);

  @protected
  PortFollowOutcomeDto dco_decode_port_follow_outcome_dto(dynamic raw);

  @protected
  PortFollowOutcomeKindDto dco_decode_port_follow_outcome_kind_dto(dynamic raw);

  @protected
  PortFollowPolicyDto dco_decode_port_follow_policy_dto(dynamic raw);

  @protected
  SignedRequest dco_decode_signed_request(dynamic raw);

  @protected
  TunnelCheckDto dco_decode_tunnel_check_dto(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  WarrenErrorKind dco_decode_warren_error_kind(dynamic raw);

  @protected
  WarrenFatalCauseDto dco_decode_warren_fatal_cause_dto(dynamic raw);

  @protected
  WarrenFfiError dco_decode_warren_ffi_error(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  WarrenClientFrb
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenClientFrb(
          SseDeserializer deserializer);

  @protected
  WarrenForwardedPortFrb
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenForwardedPortFrb(
          SseDeserializer deserializer);

  @protected
  WarrenSessionFrb
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenSessionFrb(
          SseDeserializer deserializer);

  @protected
  WarrenClientFrb
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenClientFrb(
          SseDeserializer deserializer);

  @protected
  WarrenForwardedPortFrb
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenForwardedPortFrb(
          SseDeserializer deserializer);

  @protected
  WarrenSessionFrb
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenSessionFrb(
          SseDeserializer deserializer);

  @protected
  WarrenClientFrb
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenClientFrb(
          SseDeserializer deserializer);

  @protected
  WarrenForwardedPortFrb
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenForwardedPortFrb(
          SseDeserializer deserializer);

  @protected
  WarrenSessionFrb
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenSessionFrb(
          SseDeserializer deserializer);

  @protected
  RustStreamSink<bool> sse_decode_StreamSink_bool_Sse(
      SseDeserializer deserializer);

  @protected
  RustStreamSink<ConnectionStateDto>
      sse_decode_StreamSink_connection_state_dto_Sse(
          SseDeserializer deserializer);

  @protected
  RustStreamSink<MigrationEventDto>
      sse_decode_StreamSink_migration_event_dto_Sse(
          SseDeserializer deserializer);

  @protected
  RustStreamSink<int?> sse_decode_StreamSink_opt_box_autoadd_u_16_Sse(
      SseDeserializer deserializer);

  @protected
  RustStreamSink<PortFollowOutcomeDto>
      sse_decode_StreamSink_port_follow_outcome_dto_Sse(
          SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  WarrenFatalCauseDto sse_decode_box_autoadd_warren_fatal_cause_dto(
      SseDeserializer deserializer);

  @protected
  ConnectionStateDto sse_decode_connection_state_dto(
      SseDeserializer deserializer);

  @protected
  ExitInfoDto sse_decode_exit_info_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<ExitInfoDto> sse_decode_list_exit_info_dto(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  MapProtoDto sse_decode_map_proto_dto(SseDeserializer deserializer);

  @protected
  MigrationEventDto sse_decode_migration_event_dto(
      SseDeserializer deserializer);

  @protected
  MigrationOutcomeDto sse_decode_migration_outcome_dto(
      SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  WarrenFatalCauseDto? sse_decode_opt_box_autoadd_warren_fatal_cause_dto(
      SseDeserializer deserializer);

  @protected
  PortFollowOutcomeDto sse_decode_port_follow_outcome_dto(
      SseDeserializer deserializer);

  @protected
  PortFollowOutcomeKindDto sse_decode_port_follow_outcome_kind_dto(
      SseDeserializer deserializer);

  @protected
  PortFollowPolicyDto sse_decode_port_follow_policy_dto(
      SseDeserializer deserializer);

  @protected
  SignedRequest sse_decode_signed_request(SseDeserializer deserializer);

  @protected
  TunnelCheckDto sse_decode_tunnel_check_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  WarrenErrorKind sse_decode_warren_error_kind(SseDeserializer deserializer);

  @protected
  WarrenFatalCauseDto sse_decode_warren_fatal_cause_dto(
      SseDeserializer deserializer);

  @protected
  WarrenFfiError sse_decode_warren_ffi_error(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenClientFrb(
          WarrenClientFrb self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenForwardedPortFrb(
          WarrenForwardedPortFrb self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenSessionFrb(
          WarrenSessionFrb self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenClientFrb(
          WarrenClientFrb self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenForwardedPortFrb(
          WarrenForwardedPortFrb self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenSessionFrb(
          WarrenSessionFrb self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenClientFrb(
          WarrenClientFrb self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenForwardedPortFrb(
          WarrenForwardedPortFrb self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenSessionFrb(
          WarrenSessionFrb self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_bool_Sse(
      RustStreamSink<bool> self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_connection_state_dto_Sse(
      RustStreamSink<ConnectionStateDto> self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_migration_event_dto_Sse(
      RustStreamSink<MigrationEventDto> self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_opt_box_autoadd_u_16_Sse(
      RustStreamSink<int?> self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_port_follow_outcome_dto_Sse(
      RustStreamSink<PortFollowOutcomeDto> self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_warren_fatal_cause_dto(
      WarrenFatalCauseDto self, SseSerializer serializer);

  @protected
  void sse_encode_connection_state_dto(
      ConnectionStateDto self, SseSerializer serializer);

  @protected
  void sse_encode_exit_info_dto(ExitInfoDto self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_exit_info_dto(
      List<ExitInfoDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_map_proto_dto(MapProtoDto self, SseSerializer serializer);

  @protected
  void sse_encode_migration_event_dto(
      MigrationEventDto self, SseSerializer serializer);

  @protected
  void sse_encode_migration_outcome_dto(
      MigrationOutcomeDto self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_16(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_warren_fatal_cause_dto(
      WarrenFatalCauseDto? self, SseSerializer serializer);

  @protected
  void sse_encode_port_follow_outcome_dto(
      PortFollowOutcomeDto self, SseSerializer serializer);

  @protected
  void sse_encode_port_follow_outcome_kind_dto(
      PortFollowOutcomeKindDto self, SseSerializer serializer);

  @protected
  void sse_encode_port_follow_policy_dto(
      PortFollowPolicyDto self, SseSerializer serializer);

  @protected
  void sse_encode_signed_request(SignedRequest self, SseSerializer serializer);

  @protected
  void sse_encode_tunnel_check_dto(
      TunnelCheckDto self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_warren_error_kind(
      WarrenErrorKind self, SseSerializer serializer);

  @protected
  void sse_encode_warren_fatal_cause_dto(
      WarrenFatalCauseDto self, SseSerializer serializer);

  @protected
  void sse_encode_warren_ffi_error(
      WarrenFfiError self, SseSerializer serializer);
}

// Section: wire_class

class WarrenRustBridgeWire implements BaseWire {
  WarrenRustBridgeWire.fromExternalLibrary(ExternalLibrary lib);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenClientFrb(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenClientFrb(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenClientFrb(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenClientFrb(
              ptr);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenForwardedPortFrb(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenForwardedPortFrb(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenForwardedPortFrb(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenForwardedPortFrb(
              ptr);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenSessionFrb(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenSessionFrb(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenSessionFrb(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenSessionFrb(
              ptr);
}

@JS('wasm_bindgen')
external WarrenRustBridgeWasmModule get wasmModule;

@JS()
@anonymous
extension type WarrenRustBridgeWasmModule._(JSObject _) implements JSObject {
  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenClientFrb(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenClientFrb(
          int ptr);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenForwardedPortFrb(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenForwardedPortFrb(
          int ptr);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenSessionFrb(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWarrenSessionFrb(
          int ptr);
}
