//! flutter_rust_bridge glue for the Warren engine (Mode A, in-process).
//!
//! This crate is a thin delegation layer: every function forwards to the audited
//! `warren-sdk` engine. No protocol logic lives here. flutter_rust_bridge scans
//! the `api` module and generates the Dart bindings consumed by
//! `warren_sdk_ffi`.
//!
//! No-log discipline: errors crossing the bridge are redacted and never carry a
//! pubkey, address, IP, nonce or seed in clear.

pub mod api;

// Generated by `flutter_rust_bridge_codegen`. Created on first codegen run; not
// checked in until P1 wires it up.
#[cfg(frb_generated)]
mod frb_generated;
