//! flutter_rust_bridge glue for the Warren engine (Mode A, in-process).
//!
//! This crate is a thin delegation layer: every function forwards to the audited
//! `warren-sdk` engine. No protocol logic lives here. flutter_rust_bridge scans
//! the `api` module and generates the Dart bindings consumed by
//! `warren_sdk_ffi`.
//!
//! No-log discipline: errors crossing the bridge are redacted and never carry a
//! pubkey, address, IP, nonce or seed in clear.

pub mod api;

// Generated by `flutter_rust_bridge_codegen`; regenerate with `melos run gen`.
// Checked in so the crate builds without the codegen toolchain present.
#[cfg(not(frb_expand))]
mod frb_generated;
