//! Kill-switch persistence, recovery and the lockdown block.
//!
//! The engine datapath guards are RAII: they revert on a clean teardown. On an
//! UNEXPECTED daemon end no destructor runs (release builds abort on panic,
//! SIGKILL runs nothing), so the kernel-side artifacts the engine installed
//! keep holding: the kill-switch ruleset (Linux `nft` table, macOS pf anchor)
//! and the DNS override. That is the fail-closed contract
//! (`warren_contract::killswitch`): a dead daemon must never open the network.
//!
//! This module is the non-bricking counterpart. It knows every artifact a dead
//! warrend (or engine session) can leave behind and can:
//!
//! - DETECT them (`startup_reconcile`): a fresh daemon reports the stale block
//!   and holds it, fail-closed, until a user intent arrives;
//! - CLEAR them (`revert_network`): the `warrend revert` manual escape and the
//!   clean-stop paths tear the block down and restore DNS with no healthy
//!   daemon required;
//! - REPLACE them with the lockdown block: a warrend-owned block-all artifact
//!   (its OWN nft table / pf anchor, distinct from the engine's) installed
//!   BEFORE the engine teardown on lockdown stops, so the network is never
//!   open in between. The engine teardown cannot touch it precisely because
//!   the names differ.
//!
//! Artifact names come from the engine (`warrenguard-killswitch-os`) so the
//! recovery paths can never drift from what the engine installs. Everything
//! here compiles on every host (the engine's own pattern) so both backends'
//! lifecycles are behaviorally testable anywhere; only `platform_backend`
//! selects at runtime.

use std::path::Path;

use anyhow::{Context, Result};
use warrenguard_tun_core::WARREN_TUNNEL_FWMARK;

use crate::cmd::CmdRunner;

/// The engine's Linux kill-switch table (`warrenguard_killswitch_os`).
pub const ENGINE_NFT_TABLE: &str = warrenguard_killswitch_os::NFT_TABLE_NAME;

/// The engine's macOS pf anchor. Mirrored as a plain literal so the pf backend
/// compiles (and its lifecycle tests run) on every host; the engine exports the
/// const only on macOS, where `engine_pf_anchor_matches_the_engine_export`
/// pins this copy to it.
pub const ENGINE_PF_ANCHOR: &str = "com.apple/250.warrenguard_killswitch_os";

/// warrend's own lockdown table / anchor. Deliberately NOT the engine names:
/// the engine's RAII teardown flushes its own artifact on drop, and the
/// lockdown block must survive exactly that teardown. The connecting guard
/// ([`connecting_guard_nft_ruleset`]) shares this table so a dial can transition
/// between the strict block and the guard with the same atomic replace, never an
/// open instant.
pub const LOCKDOWN_NFT_TABLE: &str = "warrend_lockdown";
/// pf twin of [`LOCKDOWN_NFT_TABLE`]. Same `com.apple/` prefix trick as the
/// engine: the stock pf.conf evaluates every `com.apple/*` sub-anchor, so the
/// block needs no pf.conf edit.
pub const LOCKDOWN_PF_ANCHOR: &str = "com.apple/251.warrend_lockdown";

/// The uid warrend itself runs as: root, because the TUN datapath needs
/// privilege. Used only by the macOS pf connecting guard, which still permits
/// warrend by owner-uid (the Mullvad `user root` pattern the app's talpid
/// firewall also uses): pf cannot match a Linux `SO_MARK`, and the engine does
/// not yet bind the control-plane client's sockets to the physical interface via
/// `IP_BOUND_IF` (the macOS analogue of the mark), so an interface-scoped pf pass
/// is not yet possible. The Linux nft guard has moved OFF owner-uid to the
/// tighter `meta mark` rule (see [`connecting_guard_nft_ruleset`]).
const DAEMON_UID: u32 = 0;

/// The engine's Linux DNS-push backup file (`dns_push.rs`). The path is
/// private in the engine, so it is mirrored here; the marker below is what the
/// engine writes into its generated resolv.conf, and both are pinned by tests
/// against the engine's public `build_resolv_conf`.
#[cfg_attr(target_os = "macos", allow(dead_code))]
pub const RESOLV_CONF_PATH: &str = "/etc/resolv.conf";
/// See [`RESOLV_CONF_PATH`].
#[cfg_attr(target_os = "macos", allow(dead_code))]
pub const RESOLV_CONF_BACKUP_PATH: &str = "/etc/resolv.conf.warrenguard.bak";
/// Ownership marker in an engine-generated resolv.conf.
#[cfg_attr(target_os = "macos", allow(dead_code))]
pub const RESOLV_CONF_MARKER: &str = "Generated by warrenguard";

/// Outcome of clearing one firewall artifact.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Cleared {
    /// The artifact existed and was removed.
    Removed,
    /// Nothing was installed (the desired end state already).
    AlreadyAbsent,
}

/// The nftables ruleset implementing the lockdown block. Same atomic
/// `add + flush + declare` pattern as the engine ruleset: re-installing
/// replaces in place with no open window. Policy drop with only loopback and
/// DHCP (lease renewal) excepted: no clear traffic escapes while no tunnel is
/// up.
#[must_use]
pub fn lockdown_nft_ruleset() -> String {
    format!(
        "add table inet {t}\n\
         flush table inet {t}\n\
         table inet {t} {{\n\
         \tchain output {{\n\
         \t\ttype filter hook output priority 0; policy drop;\n\
         \t\toifname \"lo\" accept\n\
         \t\tudp dport {{67, 68}} accept\n\
         \t}}\n\
         }}\n",
        t = LOCKDOWN_NFT_TABLE
    )
}

/// The pf rules implementing the lockdown block. The default block is FIRST
/// and NON-quick, the exceptions are `quick` passes: pf stops at the first
/// `quick` match, so a quick block would preempt the exceptions and a
/// non-quick pass could be overridden by later rules (the engine's proven
/// shape, see warrenguard-killswitch-os macos.rs).
#[must_use]
pub fn lockdown_pf_rules() -> &'static str {
    "block return out all\n\
     pass out quick on lo0 all\n\
     pass out quick proto udp from any to any port 67\n\
     pass out quick proto udp from any to any port 68\n"
}

/// The nftables ruleset for the CONNECTING GUARD: the lockdown block plus one
/// fwmark exception (`meta mark <WARREN_TUNNEL_FWMARK> accept`) so warrend's OWN
/// marked sockets (the QUIC carrier and, since the engine tags the control-plane
/// HTTP client, the directory/API fetch) can dial while every OTHER process,
/// even root-owned, stays blocked. This is the WireGuard fwmark model already
/// used for the carrier: keyed on the SOCKET, not on owner-uid, so it is strictly
/// tighter than the previous `meta skuid 0 accept` (which let ANY root process
/// egress during the window) and opens no destination hole (no Port-Fail leak).
/// Same warrend-owned table + atomic replace as the strict block, so a dial swaps
/// between the two with no open instant.
///
/// DNS caveat: the control-plane resolves names via `getaddrinfo`, whose sockets
/// are libc-internal and cannot be marked, so under this strict mark-only guard
/// the lockdown/reconnect path needs a companion (a marked resolver, or a narrow
/// DNS allowance) before it fully resolves. The common first-connect path is
/// unaffected: it dials with the firewall open (no guard), see `connect_orchestrated`.
#[must_use]
pub fn connecting_guard_nft_ruleset() -> String {
    format!(
        "add table inet {t}\n\
         flush table inet {t}\n\
         table inet {t} {{\n\
         \tchain output {{\n\
         \t\ttype filter hook output priority 0; policy drop;\n\
         \t\toifname \"lo\" accept\n\
         \t\tudp dport {{67, 68}} accept\n\
         \t\tmeta mark {mark:#x} accept\n\
         \t}}\n\
         }}\n",
        t = LOCKDOWN_NFT_TABLE,
        mark = WARREN_TUNNEL_FWMARK
    )
}

/// The pf rules for the CONNECTING GUARD: the lockdown block plus one owner-uid
/// `quick` pass so warrend's own sockets (uid `DAEMON_UID`) egress during a dial
/// while everything else stays blocked. pf cannot match a Linux SO_MARK, so the
/// owner-uid match is the macOS equivalent (and the same primitive the app's
/// talpid pf firewall uses via `user root`). The Linux guard tightened this to a
/// per-socket fwmark; the macOS analogue is to `IP_BOUND_IF` the control-plane
/// client's sockets to the physical interface and interface-scope this pass. That
/// engine `IP_BOUND_IF` binding is a follow-up, so macOS stays uid-scoped here.
#[must_use]
pub fn connecting_guard_pf_rules() -> String {
    format!(
        "block return out all\n\
         pass out quick on lo0 all\n\
         pass out quick proto udp from any to any port 67\n\
         pass out quick proto udp from any to any port 68\n\
         pass out quick from any to any user = {uid}\n",
        uid = DAEMON_UID
    )
}

/// Linux nftables backend: the engine table plus warrend's lockdown table.
#[derive(Debug, Default, Clone, Copy)]
pub struct NftBackend;

/// True when the teardown failure only says the table was already gone.
fn nft_already_absent(stderr: &str) -> bool {
    stderr.contains("No such") || stderr.contains("does not exist")
}

impl NftBackend {
    fn table_present(self, runner: &dyn CmdRunner, table: &str) -> Result<bool> {
        let out = runner
            .run("nft", &["list", "table", "inet", table], None)
            .context("spawn nft list")?;
        Ok(out.success)
    }

    fn delete_table(self, runner: &dyn CmdRunner, table: &str) -> Result<Cleared> {
        let out = runner
            .run("nft", &["delete", "table", "inet", table], None)
            .context("spawn nft delete")?;
        if out.success {
            return Ok(Cleared::Removed);
        }
        if nft_already_absent(&out.stderr) {
            return Ok(Cleared::AlreadyAbsent);
        }
        anyhow::bail!("nft delete table {table} failed: {}", out.stderr.trim());
    }

    /// Whether the engine's kill-switch table is installed.
    ///
    /// # Errors
    /// When `nft` cannot be spawned.
    pub fn engine_block_present(self, runner: &dyn CmdRunner) -> Result<bool> {
        self.table_present(runner, ENGINE_NFT_TABLE)
    }

    /// Removes the engine's kill-switch table. Idempotent.
    ///
    /// # Errors
    /// When `nft` cannot be spawned or fails for a reason other than the
    /// table being absent.
    pub fn clear_engine_block(self, runner: &dyn CmdRunner) -> Result<Cleared> {
        self.delete_table(runner, ENGINE_NFT_TABLE)
    }

    /// Whether warrend's lockdown table is installed.
    ///
    /// # Errors
    /// When `nft` cannot be spawned.
    pub fn lockdown_present(self, runner: &dyn CmdRunner) -> Result<bool> {
        self.table_present(runner, LOCKDOWN_NFT_TABLE)
    }

    /// Installs (or atomically re-installs) the lockdown block.
    ///
    /// # Errors
    /// When `nft` cannot be spawned or rejects the ruleset.
    pub fn install_lockdown(self, runner: &dyn CmdRunner) -> Result<()> {
        self.pipe_ruleset(runner, &lockdown_nft_ruleset(), "lockdown")
    }

    /// Installs (or atomically re-installs) the connecting guard: the lockdown
    /// block with the owner-uid exception that lets warrend's own dial out.
    ///
    /// # Errors
    /// When `nft` cannot be spawned or rejects the ruleset.
    pub fn install_connecting_guard(self, runner: &dyn CmdRunner) -> Result<()> {
        self.pipe_ruleset(runner, &connecting_guard_nft_ruleset(), "connecting guard")
    }

    fn pipe_ruleset(self, runner: &dyn CmdRunner, ruleset: &str, what: &str) -> Result<()> {
        let out = runner
            .run("nft", &["-f", "-"], Some(ruleset))
            .context("spawn nft -f -")?;
        anyhow::ensure!(
            out.success,
            "nft rejected the {what} ruleset: {}",
            out.stderr.trim()
        );
        Ok(())
    }

    /// Removes the lockdown block. Idempotent.
    ///
    /// # Errors
    /// Same conditions as [`Self::clear_engine_block`].
    pub fn clear_lockdown(self, runner: &dyn CmdRunner) -> Result<Cleared> {
        self.delete_table(runner, LOCKDOWN_NFT_TABLE)
    }
}

/// macOS pf backend: the engine anchor plus warrend's lockdown anchor.
#[derive(Debug, Default, Clone, Copy)]
pub struct PfBackend;

/// True when the pf failure only says the anchor was never there.
fn pf_already_absent(stderr: &str) -> bool {
    stderr.contains("does not exist") || stderr.contains("No such")
}

impl PfBackend {
    fn anchor_present(self, runner: &dyn CmdRunner, anchor: &str) -> Result<bool> {
        let out = runner
            .run("pfctl", &["-a", anchor, "-sr"], None)
            .context("spawn pfctl -sr")?;
        // An existing-but-empty anchor holds no rules: not a block.
        Ok(out.success && !out.stdout.trim().is_empty())
    }

    fn flush_anchor(self, runner: &dyn CmdRunner, anchor: &str) -> Result<Cleared> {
        let out = runner
            .run("pfctl", &["-a", anchor, "-F", "rules"], None)
            .context("spawn pfctl -F")?;
        if out.success {
            return Ok(Cleared::Removed);
        }
        if pf_already_absent(&out.stderr) {
            return Ok(Cleared::AlreadyAbsent);
        }
        anyhow::bail!("pfctl flush of {anchor} failed: {}", out.stderr.trim());
    }

    /// Whether the engine's kill-switch anchor holds rules.
    ///
    /// # Errors
    /// When `pfctl` cannot be spawned.
    pub fn engine_block_present(self, runner: &dyn CmdRunner) -> Result<bool> {
        self.anchor_present(runner, ENGINE_PF_ANCHOR)
    }

    /// Flushes the engine's kill-switch anchor. Idempotent. pf itself is left
    /// enabled: only the dead daemon knew whether IT enabled pf, and an empty
    /// Warren anchor under an enabled pf passes everything anyway.
    ///
    /// # Errors
    /// When `pfctl` cannot be spawned or fails for a reason other than the
    /// anchor being absent.
    pub fn clear_engine_block(self, runner: &dyn CmdRunner) -> Result<Cleared> {
        self.flush_anchor(runner, ENGINE_PF_ANCHOR)
    }

    /// Whether warrend's lockdown anchor holds rules.
    ///
    /// # Errors
    /// When `pfctl` cannot be spawned.
    pub fn lockdown_present(self, runner: &dyn CmdRunner) -> Result<bool> {
        self.anchor_present(runner, LOCKDOWN_PF_ANCHOR)
    }

    /// Installs (or re-installs) the lockdown block and makes sure pf is
    /// enabled so it actually filters (`-E` is the reference-counted enable
    /// the engine also uses).
    ///
    /// # Errors
    /// When `pfctl` cannot be spawned or rejects the rules.
    pub fn install_lockdown(self, runner: &dyn CmdRunner) -> Result<()> {
        self.enable_and_load(runner, lockdown_pf_rules(), "lockdown")
    }

    /// Installs (or re-installs) the connecting guard: the lockdown block plus
    /// the owner-uid pass that lets warrend's own dial out while everything else
    /// stays blocked. Enables pf like [`Self::install_lockdown`].
    ///
    /// # Errors
    /// When `pfctl` cannot be spawned or rejects the rules.
    pub fn install_connecting_guard(self, runner: &dyn CmdRunner) -> Result<()> {
        self.enable_and_load(runner, &connecting_guard_pf_rules(), "connecting guard")
    }

    fn enable_and_load(self, runner: &dyn CmdRunner, rules: &str, what: &str) -> Result<()> {
        let enable = runner
            .run("pfctl", &["-E"], None)
            .context("spawn pfctl -E")?;
        anyhow::ensure!(enable.success, "pfctl -E failed: {}", enable.stderr.trim());
        let out = runner
            .run("pfctl", &["-a", LOCKDOWN_PF_ANCHOR, "-f", "-"], Some(rules))
            .context("spawn pfctl -f")?;
        anyhow::ensure!(
            out.success,
            "pfctl rejected the {what} rules: {}",
            out.stderr.trim()
        );
        Ok(())
    }

    /// Flushes the lockdown anchor. Idempotent.
    ///
    /// # Errors
    /// Same conditions as [`Self::clear_engine_block`].
    pub fn clear_lockdown(self, runner: &dyn CmdRunner) -> Result<Cleared> {
        self.flush_anchor(runner, LOCKDOWN_PF_ANCHOR)
    }
}

/// The firewall backend for one host.
#[derive(Debug, Clone, Copy)]
pub enum Backend {
    /// Linux nftables.
    Nft(NftBackend),
    /// macOS pf.
    Pf(PfBackend),
}

/// The backend this host actually filters with.
#[must_use]
pub fn platform_backend() -> Backend {
    if cfg!(target_os = "macos") {
        Backend::Pf(PfBackend)
    } else {
        Backend::Nft(NftBackend)
    }
}

impl Backend {
    /// See the per-backend method.
    ///
    /// # Errors
    /// Propagated from the backend.
    pub fn engine_block_present(self, runner: &dyn CmdRunner) -> Result<bool> {
        match self {
            Backend::Nft(b) => b.engine_block_present(runner),
            Backend::Pf(b) => b.engine_block_present(runner),
        }
    }

    /// See the per-backend method.
    ///
    /// # Errors
    /// Propagated from the backend.
    pub fn clear_engine_block(self, runner: &dyn CmdRunner) -> Result<Cleared> {
        match self {
            Backend::Nft(b) => b.clear_engine_block(runner),
            Backend::Pf(b) => b.clear_engine_block(runner),
        }
    }

    /// See the per-backend method.
    ///
    /// # Errors
    /// Propagated from the backend.
    pub fn lockdown_present(self, runner: &dyn CmdRunner) -> Result<bool> {
        match self {
            Backend::Nft(b) => b.lockdown_present(runner),
            Backend::Pf(b) => b.lockdown_present(runner),
        }
    }

    /// See the per-backend method.
    ///
    /// # Errors
    /// Propagated from the backend.
    pub fn install_lockdown(self, runner: &dyn CmdRunner) -> Result<()> {
        match self {
            Backend::Nft(b) => b.install_lockdown(runner),
            Backend::Pf(b) => b.install_lockdown(runner),
        }
    }

    /// See the per-backend method.
    ///
    /// # Errors
    /// Propagated from the backend.
    pub fn install_connecting_guard(self, runner: &dyn CmdRunner) -> Result<()> {
        match self {
            Backend::Nft(b) => b.install_connecting_guard(runner),
            Backend::Pf(b) => b.install_connecting_guard(runner),
        }
    }

    /// See the per-backend method.
    ///
    /// # Errors
    /// Propagated from the backend.
    pub fn clear_lockdown(self, runner: &dyn CmdRunner) -> Result<Cleared> {
        match self {
            Backend::Nft(b) => b.clear_lockdown(runner),
            Backend::Pf(b) => b.clear_lockdown(runner),
        }
    }
}

/// What the Linux DNS reconcile did.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(target_os = "macos", allow(dead_code))]
pub enum DnsReconcile {
    /// resolv.conf still carried the engine override; the pre-tunnel backup
    /// was restored over it.
    RestoredBackup,
    /// A backup existed but resolv.conf had already been rewritten by
    /// something else (a network manager, the admin): the current config is
    /// the live truth, so the stale backup was removed to unblock the next
    /// engine install (which refuses to overwrite an existing backup).
    RemovedStaleBackup,
    /// Nothing to do.
    Clean,
}

/// Reconciles the engine's resolv.conf override after an unclean end, on the
/// given paths (parameterized for tests; production passes the real paths).
///
/// # Errors
/// Filesystem errors reading/renaming/removing the involved files.
#[cfg_attr(target_os = "macos", allow(dead_code))]
pub fn reconcile_dns_files(resolv_conf: &Path, backup: &Path) -> std::io::Result<DnsReconcile> {
    if !backup.exists() {
        return Ok(DnsReconcile::Clean);
    }
    let current = std::fs::read_to_string(resolv_conf).unwrap_or_default();
    if current.contains(RESOLV_CONF_MARKER) {
        // resolv.conf is often not a plain file (a symlink under
        // systemd-resolved, a per-netns bind mount in containers), where a
        // rename fails EXDEV/EBUSY; writing through the path covers those.
        if std::fs::rename(backup, resolv_conf).is_err() {
            std::fs::write(resolv_conf, std::fs::read(backup)?)?;
            std::fs::remove_file(backup)?;
        }
        return Ok(DnsReconcile::RestoredBackup);
    }
    std::fs::remove_file(backup)?;
    Ok(DnsReconcile::RemovedStaleBackup)
}

/// Reconciles the system DNS override a dead session can leave behind.
/// Returns human-readable lines describing what was done (empty = clean).
/// An unprivileged daemon (a test run) leaves DNS alone: it never pushed an
/// override, so one it finds belongs to a session it does not own.
///
/// # Errors
/// Filesystem errors on the resolv.conf paths.
#[cfg(not(target_os = "macos"))]
pub fn reconcile_dns(runner: &dyn CmdRunner) -> Result<Vec<String>> {
    if !runner.privileged() {
        return Ok(Vec::new());
    }
    let outcome = reconcile_dns_files(
        Path::new(RESOLV_CONF_PATH),
        Path::new(RESOLV_CONF_BACKUP_PATH),
    )
    .context("reconcile resolv.conf")?;
    Ok(match outcome {
        DnsReconcile::RestoredBackup => {
            vec!["restored the pre-tunnel /etc/resolv.conf from the engine backup".to_owned()]
        }
        DnsReconcile::RemovedStaleBackup => {
            vec!["removed a stale engine resolv.conf backup (current config kept)".to_owned()]
        }
        DnsReconcile::Clean => Vec::new(),
    })
}

/// macOS: the engine's DNS push overrides every enabled network service with
/// the in-tunnel gateway resolver, and its per-service restore snapshot lives
/// only in the dead daemon's memory. Detect services still pinned to exactly
/// that override and reset them to DHCP (`Empty`). A service the user had on
/// MANUAL resolvers before the crash comes back as DHCP, not the manual list:
/// the snapshot died with the daemon and DHCP restores connectivity, which is
/// the non-bricking priority. An unprivileged daemon (a test run) leaves DNS
/// alone: it never pushed an override, so one it finds belongs to a session it
/// does not own.
///
/// # Errors
/// When `networksetup` cannot be spawned or enumeration fails.
#[cfg(target_os = "macos")]
pub fn reconcile_dns(runner: &dyn CmdRunner) -> Result<Vec<String>> {
    use warrenguard_route_split::dns_push_macos::{parse_getdnsservers, parse_listall_services};

    if !runner.privileged() {
        return Ok(Vec::new());
    }

    let list = runner
        .run("networksetup", &["-listallnetworkservices"], None)
        .context("spawn networksetup -listallnetworkservices")?;
    anyhow::ensure!(
        list.success,
        "networksetup -listallnetworkservices failed: {}",
        list.stderr.trim()
    );
    let mut actions = Vec::new();
    for service in parse_listall_services(&list.stdout) {
        let current = runner
            .run("networksetup", &["-getdnsservers", &service], None)
            .context("spawn networksetup -getdnsservers")?;
        if !current.success {
            continue;
        }
        if !dns_config_is_engine_override(&parse_getdnsservers(&current.stdout)) {
            continue;
        }
        let reset = runner
            .run("networksetup", &["-setdnsservers", &service, "Empty"], None)
            .context("spawn networksetup -setdnsservers")?;
        if reset.success {
            actions.push(format!(
                "reset DNS of service {service:?} from the dead tunnel resolver to DHCP"
            ));
        } else {
            actions.push(format!(
                "FAILED to reset DNS of service {service:?}: {}",
                reset.stderr.trim()
            ));
        }
    }
    Ok(actions)
}

/// True iff a service's DNS config is exactly the engine's in-tunnel override
/// (only then may the reconcile touch it).
#[cfg(target_os = "macos")]
fn dns_config_is_engine_override(
    config: &warrenguard_route_split::dns_push_macos::DnsConfig,
) -> bool {
    use warrenguard_route_split::dns_push_macos::DnsConfig;
    matches!(config, DnsConfig::Manual(ips) if ips.as_slice() == [warrenguard_config::TUNNEL_GATEWAY_IP])
}

/// What a fresh daemon found (and did NOT clear) at startup.
#[derive(Debug)]
pub struct StaleReport {
    /// The engine kill-switch artifact is installed with no live session.
    pub engine_block: bool,
    /// warrend's lockdown artifact is installed.
    pub lockdown_block: bool,
    /// DNS reconcile actions taken (DNS is session state, not posture, so it
    /// IS reconciled at startup; the firewall block is held).
    pub dns_actions: Vec<String>,
}

/// Detects a dead predecessor's leftovers. Holds every firewall block
/// (fail-closed until a user intent arrives) but reconciles DNS immediately:
/// a stale resolver override would wedge the next connect's control-plane
/// dial, and restoring name resolution opens no traffic path while the block
/// holds.
///
/// # Errors
/// Propagated from detection / DNS reconcile.
pub fn startup_reconcile(backend: Backend, runner: &dyn CmdRunner) -> Result<StaleReport> {
    Ok(StaleReport {
        engine_block: backend.engine_block_present(runner)?,
        lockdown_block: backend.lockdown_present(runner)?,
        dns_actions: reconcile_dns(runner)?,
    })
}

/// What a full revert did.
#[derive(Debug)]
pub struct RevertReport {
    /// Engine kill-switch artifact.
    pub engine_block: Cleared,
    /// warrend lockdown artifact.
    pub lockdown_block: Cleared,
    /// DNS reconcile actions taken.
    pub dns_actions: Vec<String>,
}

/// Tears down every Warren network block this host can carry and reconciles
/// DNS. This is the `warrend revert` manual escape and the clean-stop
/// stale-state sweep; it needs no daemon and no session state.
///
/// # Errors
/// The first teardown step that fails for a real reason (not "already
/// absent"); nothing is rolled back, rerunning is safe.
pub fn revert_network(backend: Backend, runner: &dyn CmdRunner) -> Result<RevertReport> {
    Ok(RevertReport {
        engine_block: backend.clear_engine_block(runner)?,
        lockdown_block: backend.clear_lockdown(runner)?,
        dns_actions: reconcile_dns(runner)?,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::cmd::testing::{fail_with, ok_with, RecordingRunner};

    // ---- lockdown rulesets (pure) ------------------------------------

    #[test]
    fn nft_lockdown_ruleset_blocks_by_default_with_loopback_and_dhcp_only() {
        let s = lockdown_nft_ruleset();
        assert!(s.contains("policy drop;"), "must fail closed:\n{s}");
        assert!(s.contains("oifname \"lo\" accept"), "loopback stays usable");
        assert!(s.contains("udp dport {67, 68} accept"), "DHCP renewal");
        assert!(
            !s.contains("meta l4proto udp accept") && !s.contains("daddr"),
            "no exit or destination exception may exist in a lockdown block:\n{s}"
        );
    }

    #[test]
    fn nft_lockdown_ruleset_uses_the_atomic_replace_pattern_on_warrends_own_table() {
        let s = lockdown_nft_ruleset();
        let add = s.find("add table inet warrend_lockdown").expect("add");
        let flush = s.find("flush table inet warrend_lockdown").expect("flush");
        let body = s.find("table inet warrend_lockdown {").expect("body");
        assert!(add < flush && flush < body, "atomic replace order:\n{s}");
        assert!(
            !s.contains(ENGINE_NFT_TABLE),
            "the lockdown block must NOT live in the engine table: the engine \
             teardown flushes that one and would open the network:\n{s}"
        );
    }

    #[test]
    fn pf_lockdown_rules_start_with_a_non_quick_block_and_quick_exceptions() {
        let rules = lockdown_pf_rules();
        let mut lines = rules.lines();
        let block = lines.next().expect("at least the block");
        assert_eq!(
            block, "block return out all",
            "the default block is first and NON-quick: a quick block would \
             preempt the pass exceptions (engine invariant)"
        );
        for line in lines {
            assert!(
                line.starts_with("pass out quick "),
                "every exception is a quick pass: {line:?}"
            );
        }
        assert!(rules.contains("on lo0"), "loopback stays usable");
        assert!(
            rules.contains("port 67") && rules.contains("port 68"),
            "DHCP"
        );
    }

    #[test]
    fn resolv_marker_matches_what_the_engine_writes() {
        // Pin the mirrored marker to the engine's real generated content, so
        // a wording change on either side breaks here instead of silently
        // disabling the reconcile.
        let generated = warrenguard_route_split::dns_push::build_resolv_conf(&[
            warrenguard_config::TUNNEL_GATEWAY_IP,
        ]);
        assert!(
            generated.contains(RESOLV_CONF_MARKER),
            "engine resolv.conf no longer carries the marker this module \
             detects: {generated:?}"
        );
    }

    #[cfg(target_os = "macos")]
    #[test]
    fn engine_pf_anchor_matches_the_engine_export() {
        assert_eq!(ENGINE_PF_ANCHOR, warrenguard_killswitch_os::PF_ANCHOR_PATH);
    }

    // ---- nft backend lifecycle (behavioral) --------------------------

    #[test]
    fn nft_clear_engine_block_invokes_the_exact_engine_teardown() {
        let runner = RecordingRunner::default();
        let cleared = NftBackend.clear_engine_block(&runner).expect("clear");
        assert_eq!(cleared, Cleared::Removed);
        let calls = runner.calls();
        assert_eq!(calls.len(), 1);
        assert_eq!(calls[0].0, "nft");
        assert_eq!(
            calls[0].1,
            ["delete", "table", "inet", "warrenguard_killswitch_os"],
            "must remove exactly the engine's table"
        );
    }

    #[test]
    fn nft_clear_tolerates_an_already_absent_table() {
        let runner = RecordingRunner::default().with_reply(
            "nft",
            "delete table",
            fail_with(
                "Error: No such file or directory; delete table inet warrenguard_killswitch_os",
            ),
        );
        let cleared = NftBackend.clear_engine_block(&runner).expect("idempotent");
        assert_eq!(cleared, Cleared::AlreadyAbsent);
    }

    #[test]
    fn nft_clear_surfaces_real_failures() {
        let runner = RecordingRunner::default().with_reply(
            "nft",
            "delete table",
            fail_with("Operation not permitted"),
        );
        NftBackend
            .clear_engine_block(&runner)
            .expect_err("a permission failure is not idempotence");
    }

    #[test]
    fn nft_detection_reads_the_table_listing() {
        let present = RecordingRunner::default();
        assert!(NftBackend.engine_block_present(&present).expect("detect"));
        let absent = RecordingRunner::default().with_reply(
            "nft",
            "list table",
            fail_with("Error: No such file or directory"),
        );
        assert!(!NftBackend.engine_block_present(&absent).expect("detect"));
        let calls = absent.calls();
        assert_eq!(
            calls[0].1,
            ["list", "table", "inet", "warrenguard_killswitch_os"]
        );
    }

    #[test]
    fn nft_install_lockdown_pipes_the_ruleset_into_nft() {
        let runner = RecordingRunner::default();
        NftBackend.install_lockdown(&runner).expect("install");
        let calls = runner.calls();
        assert_eq!(calls.len(), 1);
        assert_eq!(calls[0].0, "nft");
        assert_eq!(calls[0].1, ["-f", "-"]);
        assert_eq!(
            calls[0].2.as_deref(),
            Some(lockdown_nft_ruleset().as_str()),
            "the piped ruleset is exactly the lockdown block"
        );
    }

    #[test]
    fn nft_install_lockdown_surfaces_a_rejected_ruleset() {
        let runner =
            RecordingRunner::default().with_reply("nft", "-f -", fail_with("syntax error"));
        NftBackend
            .install_lockdown(&runner)
            .expect_err("a rejected ruleset must not read as installed");
    }

    #[test]
    fn nft_clear_lockdown_targets_warrends_own_table() {
        let runner = RecordingRunner::default();
        NftBackend.clear_lockdown(&runner).expect("clear");
        assert_eq!(
            runner.calls()[0].1,
            ["delete", "table", "inet", "warrend_lockdown"]
        );
    }

    // ---- pf backend lifecycle (behavioral) ---------------------------

    #[test]
    fn pf_detection_requires_rules_in_the_anchor() {
        let with_rules = RecordingRunner::default().with_reply(
            "pfctl",
            "-sr",
            ok_with("block return out all\n"),
        );
        assert!(PfBackend.engine_block_present(&with_rules).expect("detect"));
        assert_eq!(
            with_rules.calls()[0].1,
            ["-a", "com.apple/250.warrenguard_killswitch_os", "-sr"]
        );

        let empty = RecordingRunner::default().with_reply("pfctl", "-sr", ok_with("\n"));
        assert!(
            !PfBackend.engine_block_present(&empty).expect("detect"),
            "an existing but EMPTY anchor blocks nothing"
        );

        let missing = RecordingRunner::default().with_reply(
            "pfctl",
            "-sr",
            fail_with("pfctl: Anchor does not exist"),
        );
        assert!(!PfBackend.engine_block_present(&missing).expect("detect"));
    }

    #[test]
    fn pf_clear_engine_block_flushes_the_engine_anchor_only() {
        let runner = RecordingRunner::default();
        let cleared = PfBackend.clear_engine_block(&runner).expect("clear");
        assert_eq!(cleared, Cleared::Removed);
        assert_eq!(
            runner.calls()[0].1,
            [
                "-a",
                "com.apple/250.warrenguard_killswitch_os",
                "-F",
                "rules"
            ]
        );
    }

    #[test]
    fn pf_clear_tolerates_a_missing_anchor() {
        let runner = RecordingRunner::default().with_reply(
            "pfctl",
            "-F rules",
            fail_with("pfctl: Anchor does not exist"),
        );
        assert_eq!(
            PfBackend.clear_engine_block(&runner).expect("idempotent"),
            Cleared::AlreadyAbsent
        );
    }

    #[test]
    fn pf_install_lockdown_enables_pf_then_loads_warrends_anchor() {
        let runner = RecordingRunner::default();
        PfBackend.install_lockdown(&runner).expect("install");
        let calls = runner.calls();
        assert_eq!(calls.len(), 2, "enable + load, in that order");
        assert_eq!(calls[0].1, ["-E"], "pf must filter for the block to hold");
        assert_eq!(
            calls[1].1,
            ["-a", "com.apple/251.warrend_lockdown", "-f", "-"]
        );
        assert_eq!(
            calls[1].2.as_deref(),
            Some(lockdown_pf_rules()),
            "the loaded rules are exactly the lockdown block"
        );
    }

    #[test]
    fn pf_lockdown_lives_outside_the_engine_anchor() {
        // The engine teardown flushes ITS anchor on drop; a lockdown block in
        // the same anchor would be flushed with it, opening the network on a
        // lockdown disconnect.
        assert_ne!(LOCKDOWN_PF_ANCHOR, ENGINE_PF_ANCHOR);
        let runner = RecordingRunner::default();
        PfBackend.clear_lockdown(&runner).expect("clear");
        assert_eq!(
            runner.calls()[0].1,
            ["-a", "com.apple/251.warrend_lockdown", "-F", "rules"]
        );
    }

    // ---- DNS reconcile (Linux file logic, any host) ------------------

    fn tempdir() -> std::path::PathBuf {
        let dir = std::env::temp_dir().join(format!(
            "warrend-dns-test-{}-{:?}",
            std::process::id(),
            std::thread::current().id()
        ));
        std::fs::create_dir_all(&dir).expect("tempdir");
        dir
    }

    #[test]
    fn dns_restore_puts_the_backup_back_when_resolv_conf_is_still_ours() {
        let dir = tempdir();
        let resolv = dir.join("resolv.conf");
        let backup = dir.join("resolv.conf.bak");
        std::fs::write(
            &resolv,
            warrenguard_route_split::dns_push::build_resolv_conf(&[
                warrenguard_config::TUNNEL_GATEWAY_IP,
            ]),
        )
        .expect("write override");
        std::fs::write(&backup, "nameserver 192.168.1.1\n").expect("write backup");

        let outcome = reconcile_dns_files(&resolv, &backup).expect("reconcile");
        assert_eq!(outcome, DnsReconcile::RestoredBackup);
        assert_eq!(
            std::fs::read_to_string(&resolv).expect("read"),
            "nameserver 192.168.1.1\n",
            "the pre-tunnel config must be back in place"
        );
        assert!(!backup.exists(), "the backup was consumed by the restore");
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn dns_restore_drops_a_stale_backup_when_resolv_conf_was_rewritten_by_others() {
        let dir = tempdir();
        let resolv = dir.join("resolv.conf");
        let backup = dir.join("resolv.conf.bak");
        std::fs::write(&resolv, "# NetworkManager\nnameserver 1.1.1.1\n").expect("write foreign");
        std::fs::write(&backup, "nameserver 192.168.1.1\n").expect("write backup");

        let outcome = reconcile_dns_files(&resolv, &backup).expect("reconcile");
        assert_eq!(outcome, DnsReconcile::RemovedStaleBackup);
        assert_eq!(
            std::fs::read_to_string(&resolv).expect("read"),
            "# NetworkManager\nnameserver 1.1.1.1\n",
            "a foreign resolv.conf is the live truth and must not be clobbered"
        );
        assert!(
            !backup.exists(),
            "the stale backup must go away so the next engine install is not refused"
        );
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn dns_restore_is_a_noop_when_no_backup_exists() {
        let dir = tempdir();
        let resolv = dir.join("resolv.conf");
        std::fs::write(&resolv, "nameserver 9.9.9.9\n").expect("write");
        let outcome =
            reconcile_dns_files(&resolv, &dir.join("resolv.conf.bak")).expect("reconcile");
        assert_eq!(outcome, DnsReconcile::Clean);
        std::fs::remove_dir_all(&dir).ok();
    }

    // ---- macOS DNS reconcile (behavioral, macOS only: uses the engine's
    // cfg-gated parsers) ----------------------------------------------

    #[cfg(target_os = "macos")]
    #[test]
    fn macos_dns_reconcile_resets_only_services_pinned_to_the_tunnel_resolver() {
        let listing = "An asterisk (*) denotes that a network service is disabled.\n\
                       Wi-Fi\nThunderbolt Bridge\n*Disabled Service\n";
        let runner = RecordingRunner::default()
            .with_reply("networksetup", "-listallnetworkservices", ok_with(listing))
            .with_reply(
                "networksetup",
                "-getdnsservers Wi-Fi",
                ok_with("10.66.0.1\n"),
            )
            .with_reply(
                "networksetup",
                "-getdnsservers Thunderbolt Bridge",
                ok_with("There aren't any DNS Servers set on Thunderbolt Bridge.\n"),
            );
        let actions = reconcile_dns(&runner).expect("reconcile");
        assert_eq!(actions.len(), 1, "only the overridden service is touched");
        assert!(actions[0].contains("Wi-Fi"));

        let calls = runner.calls();
        let resets: Vec<_> = calls
            .iter()
            .filter(|(_, args, _)| args.first().map(String::as_str) == Some("-setdnsservers"))
            .collect();
        assert_eq!(resets.len(), 1);
        assert_eq!(resets[0].1, ["-setdnsservers", "Wi-Fi", "Empty"]);
    }

    #[cfg(target_os = "macos")]
    #[test]
    fn an_unprivileged_daemon_never_resets_a_services_dns() {
        // It never pushed a DNS override, so one it finds belongs to a session
        // it does not own (a root daemon on the same host).
        let listing = "An asterisk (*) denotes that a network service is disabled.\nWi-Fi\n";
        let runner = RecordingRunner::default()
            .unprivileged()
            .with_reply("networksetup", "-listallnetworkservices", ok_with(listing))
            .with_reply(
                "networksetup",
                "-getdnsservers Wi-Fi",
                ok_with("10.66.0.1\n"),
            );

        let actions = reconcile_dns(&runner).expect("reconcile");

        assert!(actions.is_empty(), "{actions:?}");
        assert!(
            !runner
                .calls()
                .iter()
                .any(|(_, args, _)| args.first().map(String::as_str) == Some("-setdnsservers")),
            "no reset may run: {:?}",
            runner.calls()
        );
    }

    #[cfg(target_os = "macos")]
    #[test]
    fn macos_dns_reconcile_leaves_manual_non_warren_resolvers_alone() {
        let listing = "An asterisk (*) denotes that a network service is disabled.\nWi-Fi\n";
        let runner = RecordingRunner::default()
            .with_reply("networksetup", "-listallnetworkservices", ok_with(listing))
            .with_reply("networksetup", "-getdnsservers Wi-Fi", ok_with("9.9.9.9\n"));
        let actions = reconcile_dns(&runner).expect("reconcile");
        assert!(
            actions.is_empty(),
            "a user's manual resolver is not ours to touch"
        );
        assert!(
            !runner
                .calls()
                .iter()
                .any(|(_, args, _)| args.first().map(String::as_str) == Some("-setdnsservers")),
            "no reset may run"
        );
    }

    // ---- orchestration -----------------------------------------------

    #[test]
    fn revert_clears_engine_and_lockdown_artifacts_on_the_nft_backend() {
        let runner = RecordingRunner::default();
        let report = revert_network(Backend::Nft(NftBackend), &runner).expect("revert");
        assert_eq!(report.engine_block, Cleared::Removed);
        assert_eq!(report.lockdown_block, Cleared::Removed);
        let tables: Vec<_> = runner
            .calls()
            .iter()
            .filter(|(p, args, _)| p == "nft" && args.first().map(String::as_str) == Some("delete"))
            .map(|(_, args, _)| args[3].clone())
            .collect();
        assert_eq!(
            tables,
            ["warrenguard_killswitch_os", "warrend_lockdown"],
            "both artifacts must go"
        );
    }

    #[test]
    fn revert_clears_engine_and_lockdown_anchors_on_the_pf_backend() {
        let runner = RecordingRunner::default();
        let report = revert_network(Backend::Pf(PfBackend), &runner).expect("revert");
        assert_eq!(report.engine_block, Cleared::Removed);
        assert_eq!(report.lockdown_block, Cleared::Removed);
        let anchors: Vec<_> = runner
            .calls()
            .iter()
            .filter(|(p, args, _)| p == "pfctl" && args.contains(&"-F".to_owned()))
            .map(|(_, args, _)| args[1].clone())
            .collect();
        assert_eq!(
            anchors,
            [
                "com.apple/250.warrenguard_killswitch_os",
                "com.apple/251.warrend_lockdown"
            ]
        );
    }

    #[test]
    fn startup_reconcile_detects_but_never_clears_firewall_blocks() {
        let runner = RecordingRunner::default().with_reply(
            "pfctl",
            "-sr",
            ok_with("block return out all\n"),
        );
        let report = startup_reconcile(Backend::Pf(PfBackend), &runner).expect("reconcile");
        assert!(report.engine_block, "the stale block must be reported");
        assert!(
            !runner
                .calls()
                .iter()
                .any(|(_, args, _)| args.contains(&"-F".to_owned())),
            "startup must HOLD the block (fail-closed), never clear it"
        );
    }

    // ---- connecting guard (item 1: no more full lift during a dial) --

    #[test]
    fn connecting_guard_nft_permits_the_daemon_mark_but_no_destination_hole() {
        let s = connecting_guard_nft_ruleset();
        assert!(s.contains("policy drop;"), "must still fail closed:\n{s}");
        assert!(s.contains("oifname \"lo\" accept"), "loopback stays usable");
        assert!(s.contains("udp dport {67, 68} accept"), "DHCP renewal");
        assert!(
            s.contains("meta mark 0x77617272 accept"),
            "the guard must permit warrend's OWN marked sockets (carrier + \
             control-plane) by fwmark, so its dial egresses while every other \
             process, even root-owned, stays blocked:\n{s}"
        );
        assert!(
            !s.contains("skuid"),
            "the tightened guard is keyed on the socket mark, NOT owner-uid: a \
             root-wide skuid allowance would let ANY root process leak out of the \
             block (the residual this change closes):\n{s}"
        );
        assert!(
            !s.contains("daddr") && !s.contains("meta l4proto udp accept"),
            "the guard is identity-based: no destination exception (that is the \
             Port-Fail hole the full lift used to open):\n{s}"
        );
        assert!(
            s.contains("table inet warrend_lockdown"),
            "the guard shares warrend's own table so it swaps atomically with the \
             strict block, never the engine table:\n{s}"
        );
    }

    #[test]
    fn connecting_guard_nft_mark_rule_matches_the_engine_carrier_fwmark() {
        // The guard permits EXACTLY the fwmark the engine tags the carrier (and,
        // since Part 1, the control-plane client) with; rendered as the same nft
        // hex the engine kill-switch uses, so guard and socket mark cannot drift.
        assert_eq!(WARREN_TUNNEL_FWMARK, 0x7761_7272);
        assert!(
            connecting_guard_nft_ruleset()
                .contains(&format!("meta mark {WARREN_TUNNEL_FWMARK:#x} accept")),
            "the guard mark rule must render the canonical fwmark constant"
        );
    }

    #[test]
    fn connecting_guard_pf_permits_the_daemon_uid_via_a_quick_pass() {
        let rules = connecting_guard_pf_rules();
        let mut lines = rules.lines();
        assert_eq!(
            lines.next(),
            Some("block return out all"),
            "the default block stays first and NON-quick"
        );
        assert!(
            rules.contains("pass out quick from any to any user = 0"),
            "pf cannot match the Linux SO_MARK, so the owner-uid pass is the macOS \
             equivalent that lets warrend's own dial out:\n{rules}"
        );
        for line in rules.lines().skip(1) {
            assert!(
                line.starts_with("pass out quick "),
                "every exception is a quick pass: {line:?}"
            );
        }
    }

    #[test]
    fn nft_install_connecting_guard_pipes_the_guard_ruleset() {
        let runner = RecordingRunner::default();
        NftBackend
            .install_connecting_guard(&runner)
            .expect("install");
        let calls = runner.calls();
        assert_eq!(calls.len(), 1);
        assert_eq!(calls[0].0, "nft");
        assert_eq!(calls[0].1, ["-f", "-"]);
        assert_eq!(
            calls[0].2.as_deref(),
            Some(connecting_guard_nft_ruleset().as_str()),
            "the piped ruleset is exactly the connecting guard"
        );
    }

    #[test]
    fn pf_install_connecting_guard_enables_pf_then_loads_the_guard_into_warrends_anchor() {
        let runner = RecordingRunner::default();
        PfBackend
            .install_connecting_guard(&runner)
            .expect("install");
        let calls = runner.calls();
        assert_eq!(calls.len(), 2, "enable + load");
        assert_eq!(calls[0].1, ["-E"]);
        assert_eq!(
            calls[1].1,
            ["-a", "com.apple/251.warrend_lockdown", "-f", "-"],
            "the guard loads into warrend's own anchor, never the engine anchor"
        );
        assert_eq!(
            calls[1].2.as_deref(),
            Some(connecting_guard_pf_rules().as_str())
        );
    }

    #[test]
    fn install_connecting_guard_dispatches_per_backend() {
        let nft = RecordingRunner::default();
        Backend::Nft(NftBackend)
            .install_connecting_guard(&nft)
            .expect("nft");
        assert_eq!(nft.calls()[0].0, "nft");
        let pf = RecordingRunner::default();
        Backend::Pf(PfBackend)
            .install_connecting_guard(&pf)
            .expect("pf");
        assert_eq!(pf.calls()[0].0, "pfctl");
    }
}
