#!/usr/bin/env bash
set -euo pipefail

# ─────────────────────────────────────────────────────────────────────
# warrend, DEV-ONLY passwordless sudo (macOS / Linux)
#
# Installs a scoped /etc/sudoers.d drop-in so the developer can run the
# Warren SDK daemon (which opens a TUN device, needs root) WITHOUT a
# password prompt, purely to exercise Mode B locally.
#
# THIS IS NOT PRODUCTION WIRING. In production the daemon is launched by a
# proper per-OS privilege bootstrap (polkit / launchd helper / Windows
# service), never a dev sudoers drop-in.
#
# The rule pins the absolute warrend binary path: no general privilege
# escalation. Validated with `visudo -c` before install.
#
# Usage:  ./scripts/dev-sudoers.sh            # install
#         ./scripts/dev-sudoers.sh --remove   # uninstall
# ─────────────────────────────────────────────────────────────────────

SUDOERS_FILE=/etc/sudoers.d/warren-sdk-dev
die() { echo "error: $*" >&2; exit 1; }

if [[ "${1:-}" == "--remove" ]]; then
  sudo rm -f "$SUDOERS_FILE"
  echo "Removed $SUDOERS_FILE."
  exit 0
fi

DEV_USER="${SUDO_USER:-$(id -un)}"
SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)
CRATE_DIR=$(cd "$SCRIPT_DIR/.." && pwd -P)
BIN="$CRATE_DIR/target/release/warrend"

[[ -f "$BIN" ]] || die "build the daemon first: (cd '$CRATE_DIR' && cargo build --release)"

tmp=$(mktemp)
trap 'rm -f "$tmp"' EXIT
cat > "$tmp" <<EOF
# Warren SDK dev-only: run the daemon as root without a prompt. Test only.
# Generated by native/warrend/scripts/dev-sudoers.sh.
$DEV_USER ALL=(root) NOPASSWD: $BIN *, $BIN
EOF

sudo visudo -c -f "$tmp" >/dev/null || die "generated sudoers failed validation; nothing installed."
sudo install -m 0440 -o root -g wheel "$tmp" "$SUDOERS_FILE" 2>/dev/null \
  || sudo install -m 0440 -o root -g root "$tmp" "$SUDOERS_FILE"
sudo visudo -c -f "$SUDOERS_FILE" >/dev/null || die "post-install validation failed (unexpected)."

echo "Installed $SUDOERS_FILE for '$DEV_USER' -> $BIN"
sudo -n "$BIN" --version >/dev/null 2>&1 || true
echo "You can now run: sudo -n '$BIN' <socket-path>"
