#!/usr/bin/env bash
set -euo pipefail

# ─────────────────────────────────────────────────────────────────────
# warrend, DEV-ONLY passwordless sudo (macOS / Linux)
#
# Installs a scoped /etc/sudoers.d drop-in so the developer can run the
# Warren SDK daemon (which opens a TUN device, needs root) WITHOUT a
# password prompt, purely to exercise Mode B locally.
#
# THIS IS NOT PRODUCTION WIRING. In production the daemon is launched by a
# proper per-OS privilege bootstrap (polkit / launchd helper / Windows
# service), never a dev sudoers drop-in.
#
# A passwordless rule hands root to anything running as the developer's
# account, so it is kept to exactly what the rooted tests need:
# - it names a root-owned COPY of the daemon in a directory only root can
#   write, never the build output, which that account can overwrite. Rerun
#   this script after every rebuild; the rooted test refuses a stale copy.
# - it pins the argument list: none (the daemon on its default socket,
#   /var/run/warrend/warrend.sock) or `revert`. No caller picks a path the
#   root daemon creates, removes or hands over.
# The daemon resets its own environment (a fixed PATH) before it spawns
# anything, so the caller's PATH cannot pick the tools root runs either.
#
# Usage:  ./scripts/dev-sudoers.sh            # install, or refresh the copy
#         ./scripts/dev-sudoers.sh --remove   # uninstall
# ─────────────────────────────────────────────────────────────────────

SUDOERS_FILE=/etc/sudoers.d/warren-sdk-dev
INSTALL_DIR=/usr/local/libexec/warren-sdk-dev
INSTALLED_BIN="$INSTALL_DIR/warrend"
die() { echo "error: $*" >&2; exit 1; }

if [[ "${1:-}" == "--remove" ]]; then
  sudo rm -f "$SUDOERS_FILE"
  sudo rm -rf "$INSTALL_DIR"
  echo "Removed $SUDOERS_FILE and $INSTALL_DIR."
  exit 0
fi

DEV_USER="${SUDO_USER:-$(id -un)}"
[[ "$DEV_USER" =~ ^[A-Za-z_][A-Za-z0-9_.-]*$ ]] || die "unexpected account name: $DEV_USER"
SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)
CRATE_DIR=$(cd "$SCRIPT_DIR/.." && pwd -P)
BIN="$CRATE_DIR/target/release/warrend"
ROOT_GROUP=$(id -gn root)

[[ -f "$BIN" ]] || die "build the daemon first: (cd '$CRATE_DIR' && cargo build --release)"

# "<owner uid> <permission bits in octal>" of a path, without following a link.
owner_and_mode() {
  if [[ "$(uname -s)" == Darwin ]]; then
    stat -f '%u %Lp' "$1"
  else
    stat -c '%u %a' "$1"
  fi
}

sudo mkdir -p "$INSTALL_DIR"
sudo chown "root:$ROOT_GROUP" "$INSTALL_DIR"
sudo chmod 0755 "$INSTALL_DIR"

# Any account that can write one directory on the way to the copy can swap it.
dir=$(cd "$INSTALL_DIR" && pwd -P)
while :; do
  read -r owner mode < <(owner_and_mode "$dir")
  [[ "$owner" == 0 ]] || die "$dir is not owned by root; pick another INSTALL_DIR"
  (( (8#$mode & 8#022) == 0 )) || die "$dir is writable by group or others; pick another INSTALL_DIR"
  [[ "$dir" == / ]] && break
  dir=$(dirname "$dir")
done

sudo install -m 0755 -o root -g "$ROOT_GROUP" "$BIN" "$INSTALLED_BIN"

tmp=$(mktemp)
trap 'rm -f "$tmp"' EXIT
cat > "$tmp" <<EOF
# Warren SDK dev-only: run a root-owned copy of the daemon without a prompt,
# with no argument or with \`revert\` only. Test only.
# Generated by native/warrend/scripts/dev-sudoers.sh.
$DEV_USER ALL=(root) NOPASSWD: $INSTALLED_BIN "", $INSTALLED_BIN revert
EOF

sudo visudo -c -f "$tmp" >/dev/null || die "generated sudoers failed validation; nothing installed."
sudo install -m 0440 -o root -g "$ROOT_GROUP" "$tmp" "$SUDOERS_FILE"
sudo visudo -c -f "$SUDOERS_FILE" >/dev/null || die "post-install validation failed (unexpected)."

echo "Installed $SUDOERS_FILE for '$DEV_USER' -> $INSTALLED_BIN (copied from $BIN)"
# Non-blocking authorization check (list mode; does not run the daemon).
if sudo -n -l "$INSTALLED_BIN" >/dev/null 2>&1; then
  echo "NOPASSWD active. You can now run: sudo -n '$INSTALLED_BIN'"
else
  die "sudoers installed but 'sudo -n -l $INSTALLED_BIN' still fails; inspect $SUDOERS_FILE."
fi
